export const IMPRESSIONS_FORMATTED = [
  {
    title: "Social and Interpersonal Qualities",
    key: "Social and Interpersonal Qualities",
    data: [
      {
        key: "Social and Interpersonal Qualities",
        list: [
          "Accessible",
          "Agreeable",
          "Amiable",
          "Caring",
          "Charismatic",
          "Charming",
          "Cheerful",
          "Compassionate",
          "Courteous",
          "Friendly",
          "Generous",
          "Genuine",
          "Good-natured",
          "Loyal",
          "Protective",
          "Sharing",
          "Sociable",
          "Sweet",
          "Understanding",
        ],
      },
    ],
  },
  {
    title: "Personality",
    key: "Personality",
    data: [
      {
        key: "Personality",
        list: [
          "Adaptable",
          "Adventurous",
          "Alert",
          "Balanced",
          "Calm",
          "Challenging",
          "Clear-headed",
          "Clever",
          "Colorful",
          "Creative",
          "Cultured",
          "Curious",
          "Daring",
          "Decisive",
          "Dramatic",
          "Elegant",
          "Empathetic",
          "Energetic",
          "Enthusiastic",
          "Exciting",
          "Focused",
          "Fun-loving",
          "Imaginative",
          "Independent",
          "Insightful",
          "Intelligent",
          "Intuitive",
          "Logical",
          "Perceptive",
          "Playful",
          "Realistic",
          "Relaxed",
          "Romantic",
          "Sensitive",
          "Spontaneous",
          "Strong",
          "Witty",
          "Youthful",
          "Busy",
          "Casual",
          "Dominating",
          "Dreamy",
          "Driving",
          "Experimental",
          "Mystical",
          "Old-fashioned",
          "Predictable",
          "Proud",
          "Quiet",
          "Self-conscious",
          "Skeptical",
          "Stable",
        ],
      },
    ],
  },
  {
    title: "Values and Ethics",
    key: "Values and Ethics",
    data: [
      {
        key: "Values and Ethics",
        list: [
          "Appreciative",
          "Aspiring",
          "Honest",
          "Humble",
          "Idealistic",
          "Modest",
          "Respectful",
          "Tolerant",
          "Wise",
          "Conservative",
          "Private",
          "Progressive",
          "Strict",
        ],
      },
    ],
  },
  {
    title: "Professional Traits",
    key: "Professional Traits",
    data: [
      {
        key: "Professional Traits",
        list: [
          "Articulate",
          "Capable",
          "Dedicated",
          "Disciplined",
          "Discreet",
          "Educated",
          "Organized",
          "Passionate",
          "Persuasive",
          "Resourceful",
          "Logical",
          "Methodical",
          "Punctual",
          "Resourceful",
        ],
      },
    ],
  },
  {
    title: "Physical Attributes",
    key: "Physical Attributes",
    data: [
      {
        key: "Physical Attributes",
        list: ["Athletic", "Healthy"],
      },
    ],
  },
];
