const screenName = {
  REQUEST_FEEDBACK_SPLASH_SCREEN: "FeedbackSplashScreen",
  FEEDBACK_IMPRESSIONS: "FeedbackImpressions",
  UNAUTHORIZEDFEEDBACKUSER: "UnauthorizedFeedbackUser",
  AUTHORIZEDFEEDBACKUSER: "AuthorizedFeedbackUser",
  USER_PROFILE_FEEDBACK: "UserProfileFeedback",
  REQUEST_FEEDBACK_PROFILE: "RequestFeedbackProfile",
  GO_DEEPER: "GoDeeper",
  ERROR_SCREEN: "ErrorScreen",
  APPLE_EMAIL: "AppleEmail",

  // Auth Stack
  LAUNCH: "Launch",
  LOGIN: "Login",
  REGISTER: "Register",
  FORGOT_PASSWORD: "ForgotPassword",
  RESET_PASSWORD: "ResetPassword",

  //   Navigators
  NAVIGATOR: "Navigator",
  APP_NAVIGATOR: "AppNavigator",
  AUTH_NAVIGATOR: "AuthNavigator",
  VOTE_NAVIGATOR: "VoteNavigator",
  CHAT_NAVIGATOR: "ChatNavigator",
  HOME_NAVIGATOR: "HomeNavigator",
  ONBOARD_NAVIGATOR: "OnboardNavigator",
  VOTE_ONBOARD_NAVIGATOR: "VoteOnboardNavigator",
  PROFILE_NAVIGATOR: "ProfileNavigator",
  FEEDBACK_NAVIGATOR: "FeedbackNavigator",
  // ONBOARD_NAVIGATION
  SHARE_FOR_FEEDBACK: "ShareForFeedback",
  NAME: "OnboardName",
  GENDER: "Gender",
  DATE_WHO: "DateWho",
  BIRTHDAY: "OnboardBirthday",
  HEIGHT: "Height",
  PHOTOS: "PhotoVideo",
  LOCATION: "GetLocations",
  NOTIFICATIONS: "SendNotification",
  QUESTION_PROMPT: "QuestionPrompt",
  ONBOARD_TEXT: "OnboardText",
  ALLPROMPTS: "AllPrompts",
  // note: PROMPT_ANSWER is used in onboard flow to point to OnboardPromptAnswer, in edit points to EditPromptAnswer
  PROMPT_ANSWER: "PromptAnswer",

  // APP_NAVIGATOR
  VOTE: "Vote",
  CHAT: "Chat",
  PROFILE_HOME: "Home",

  // PROFILE
  ANALYTICS: "Analytics",
  USER_PROFILE: "UserProfile",
  PROFILE_MODAL: "ProfileModal",
  WORK: "Work",
  EDUCATION_LEVEL: "EducationLevel",
  POLIITICS: "Politics",
  JOB_TITLE: "JobTitle",
  SCHOOL: "School",
  REGLIGIOUS_BELIEF: "ReligiousBelief",
  HOMETOWN: "Hometown",
  COMPANY: "Company",
  ETHNICITY: "Ethnicity",
  PHYSICAL_ACTIVITY: "Sports",
  SMOKING: "Smoking",
  CANNABIS: "Cannabis",
  ALCOHOL: "Alcohol",
  DRUGS: "Drugs",
  DIET: "Diet",
  LANGUAGES: "Languages",
  MUSIC_GENRES: "MusicGenre",
  BOOK_GENRES: "BookGenre",
  CREATIVE_OUTLET: "CreativeOutlet",
  RELIGIONS: "Religions",
  RELIGIOUS_PRACTICES: "ReligiousPractices",
  ZODIAC: "Zodiac",
  MEYER_BRIGGS: "MeyerBriggs",
  CHARACTERISTICS: "Characteristics",
  POLITICS: "Politics",
  PARENTING_GOALS: "ParentingGoals",
  RELATIONSHIP_GOALS: "RelationshipGoals",
  RELATIONSHIP_TYPES: "RelationshipTypes",
  PETS: "Pets",
  GOING_OUT: "GoingOut",
  STAYING_IN: "StayingIn",
  DRINK: "Drink",

  // CHAT
  CONVERSATIONS: "Conversations",
  MESSAGES: "Messages",

  // VOTE NAVIGATOR
  PROMPT_VOTE: "PromptVote",
  VISUAL_VOTE: "VisualVote",
  PROFILE_VIEW: "ProfileView",
  MATCH_VIEW: "MatchView",
  COME_BACK_LATER: "ComeBackLater",

  // HOME/PROFILE
  USER_PROFILE_EDIT: "UserProfileEdit",
  USER_PROFILE_VIEW: "UserProfileView",
  TOGGLE_PROFILE_VIEW: "ToggleProfileView",
};

export default screenName;
