import {
  Poppins_100Thin,
  Poppins_100Thin_Italic,
  Poppins_200ExtraLight,
  Poppins_200ExtraLight_Italic,
  Poppins_300Light,
  Poppins_300Light_Italic,
  Poppins_400Regular,
  Poppins_400Regular_Italic,
  Poppins_500Medium,
  Poppins_500Medium_Italic,
  Poppins_600SemiBold,
  Poppins_600SemiBold_Italic,
  Poppins_700Bold,
  Poppins_700Bold_Italic,
  Poppins_800ExtraBold,
  Poppins_800ExtraBold_Italic,
  Poppins_900Black,
  Poppins_900Black_Italic,
} from "@expo-google-fonts/poppins";
import { Coustard_400Regular, Coustard_900Black } from "@expo-google-fonts/coustard";
import {
  RobotoSerif_100Thin_Italic,
  RobotoSerif_200ExtraLight_Italic,
  RobotoSerif_300Light_Italic,
  RobotoSerif_400Regular_Italic,
  RobotoSerif_500Medium_Italic,
  RobotoSerif_600SemiBold_Italic,
  // RobotoSerif_700Bold_Italic,
  // RobotoSerif_800ExtraBold_Italic,
  // RobotoSerif_900Black_Italic,
} from "@expo-google-fonts/roboto-serif";
import {
  RobotoSlab_100Thin,
  RobotoSlab_200ExtraLight,
  RobotoSlab_300Light,
  RobotoSlab_400Regular,
  RobotoSlab_500Medium,
  RobotoSlab_600SemiBold,
  // RobotoSlab_700Bold,
  // RobotoSlab_800ExtraBold,
  // RobotoSlab_900Black,
} from "@expo-google-fonts/roboto-slab";
import { Tienne_400Regular, Tienne_700Bold, Tienne_900Black } from "@expo-google-fonts/tienne";
import { Capriola_400Regular } from "@expo-google-fonts/capriola";
import { useFonts } from "expo-font";

export const useCustomTheme = () => {
  const [fontsLoaded] = useFonts({
    Coustard_400Regular,
    Coustard_900Black,
    Poppins_100Thin,
    Poppins_100Thin_Italic,
    Poppins_200ExtraLight,
    Poppins_200ExtraLight_Italic,
    Poppins_300Light,
    Poppins_300Light_Italic,
    Poppins_400Regular,
    Poppins_400Regular_Italic,
    Poppins_500Medium,
    Poppins_500Medium_Italic,
    Poppins_600SemiBold,
    Poppins_600SemiBold_Italic,
    Poppins_700Bold,
    Poppins_700Bold_Italic,
    Poppins_800ExtraBold,
    Poppins_800ExtraBold_Italic,
    Poppins_900Black,
    Poppins_900Black_Italic,
    RobotoSlab_100Thin,
    RobotoSlab_200ExtraLight,
    RobotoSlab_300Light,
    RobotoSlab_400Regular,
    RobotoSlab_500Medium,
    RobotoSlab_600SemiBold,
    // RobotoSlab_700Bold,
    // RobotoSlab_800ExtraBold,
    // RobotoSlab_900Black,
    RobotoSerif_100Thin_Italic,
    RobotoSerif_200ExtraLight_Italic,
    RobotoSerif_300Light_Italic,
    RobotoSerif_400Regular_Italic,
    RobotoSerif_500Medium_Italic,
    RobotoSerif_600SemiBold_Italic,
    // RobotoSerif_700Bold_Italic,
    // RobotoSerif_800ExtraBold_Italic,
    // RobotoSerif_900Black_Italic,
    Tienne_400Regular,
    Tienne_700Bold,
    Tienne_900Black,
    Capriola_400Regular,
  });

  return [fontsLoaded];
};
