export const actions = {
  view: "view",
  save: "save",
  edit: "edit",
  delete: "delete",
};

export const analyticScreenNames = {
  welcome: "Welcome", // Analytics: ScreenView
  signIn: "Sign In",
  signUp: "Sign up",
  signUpOTP: "Sign Up OTP",
  forgetPassword: "Forgot Password",
  forgotPasswordOTP: "Forgot Password OTP",
  resetPassword: "Reset Password",
  forceAppUpdate: "Force App Update",
  onBoardName: "On Board Name",
  onBoardBirthday: "On Board Birthday",
  onBoardNotification: "On Board Notification",
  onBoardLocation: "On Board Location",
  onBoardGender: "On Board Gender",
  onBoardGenderPreference: "On Board Gender Preference",
  onBoardHeight: "On Board Height",
  onBoardPhotos: "On Board Photos",
  onBoardAllPrompts: "On Board All Prompts",
  onBoardAnswerPrompt: "On Board Answer Prompt",
  onBoardPrompts: "On Board Prompts",
  openingMessage: "Opening Message",
  ratePromptMessage: "Rate Prompt Message",
  ratePromptExample: "Rate Prompt Example",
  ratePhotoMessage: "Rate Photo Message",
  ratePhotoExample: "Rate Photo Example",
  ratePrompt: "Rate Prompt",
  ratePhoto: "Rate Photo",
  profileView: "Profile View",
  startConversation: "Start Conversation",
  matchMade: "Match Made",
  noMore: "No More",
  blockOrReportUser: "Block or Report User",
  scoopFeedback: "Scoop Feedback",
  profileHome: "Profile Home",
  editProfile: "Edit Profile",
  editPhoto: "Edit Photo",
  photoPromptList: "Photo Prompt List",
  selectPhotoPrompt: "Select Photo Prompt",
  preview: "Preview",
  height: "Height",
  gender: "Gender",
  location: "Location",
  jobTitle: "Job Title",
  company: "Company",
  homeTown: "Home Town",
  school: "School",
  educationLevel: "Education Level",
  goingOut: "Going Out",
  ethnicity: "Ethnicity",
  sports: "Sports",
  smoking: "Smoking",
  cannabis: "Cannabis",
  alcohol: "Alcohol",
  drink: "Drink",
  bookGenre: "Book Genre",
  drugs: "Drugs",
  diet: "Diet",
  languages: "Languages",
  musicGenre: "Music Genre",
  creativeOulet: "Creative Oulet",
  religion: "Religion",
  religiousPractice: "Religious Practice",
  zodiac: "Zodiac",
  meyerBriggs: "Meyer Briggs",
  characteristics: "Characteristics",
  politics: "politics",
  parentingGoal: "Children",
  relationshipGoals: "Relationship Goals",
  relationshipTypes: "Relationship Types",
  stayingIn: "Staying In",
  pets: "Pets",
  chatList: "Chat List",
  message: "Message",
  aboutMe: "about me",
  vote: "Vote",
  visuals: "Visuals",
  profileAllPrompts: "Profile All Prompts",
  profileAnswerPrompt: "Profile Answer Prompt",
  onBoarding: "onBoarding",
  chat: "Conversations",
  messages: "Messages",
  matches: "Matches",
  launch: "Launch",
  settings: "Settings",
  onBoardingEnd: "On Boarding End",
  profileFeedbackImpressions: "Profile Feedback Impressions",
  profileFeedbackLanding: "Profile Feedback Landing",
  profileFeedbackThankYou: "Profile Feedback Thank You",
};

export const screenClass = {
  auth: "Auth",
  appUpdate: "App Update",
  onBoarding: "On Boarding",
  tutorial: "Tutorial",
  matches: "Daily Matches",
  block: "Block",
  feedback: "Feedback",
  profile: "Profile",
  preferences: "Preferences",
  chat: "Chat",
  settings: "Settings",
};

export const eventNames = {
  redirectSignUpButton: "redirect: SignUp Button - Click",
  redirectSignInButton: "redirect: SignIn Button - Click",
  submitSignUpButtonClick: "submit: SignUp Button - Click",
  submitSignUpButtonResponse: "submit: SignUp Button - Response",
  submitAppleSignInEmail: "submit: AppleSignInEmail",
  submitOtpButton: "submit: OtpButton - Click",
  submitResendOtpButton: "submit: ResendOtp Button - Click",
  submitSignInButtonClick: "submit: SignIn Button - Click",
  submitSignInButtonResponse: "submit: SignInButton - Response",
  submitForgotPasswordButton: "submit: ForgotPassword Button - Click",
  submitOnBoardNameButton: "submit: OnBoardNameButton - Click",
  submitOnBoardBirthdayButton: "submit: OnBoardBirthday Button - Click",
  confirmOnBoardBirthdayButton: "confirm: OnBoardBirthday Button - Click",
  notificationChoice: "Notifications Choice",
  nextOnBoardNotificationButton: "next: OnBoardNotification Button - Click",
  submitOnBoardLocationButton: "submit: OnBoardLocation Button - Click",
  submitOnBoardGenderButton: "submit: OnBoardGender Button - Click",
  submitOnBoardGenderPreferenceButton: "submit: OnBoardGenderPreference Button - Click",
  submitOnBoardHeightButton: "submit: OnBoard Height Button - Click",
  addOnBoardPhotosButton: "add: OnBoard Photos Button - Click",
  editOnBoardPhotosButton: "edit: OnBoard Photos Button - Click",
  removeOnBoardPhotosButton: "remove: OnBoard Photos Button - Click",
  navigateProfileButton: "navigate: Profile Button - Click",
  navigateChatButton: "navigate: Chat Button - Click",
  navigateRateButton: "navigate: Rate Button - Click",
  editMainProfileButton: "edit: Main Profile Button - Click",
  saveProfileButton: "save: Profile Button - Click",
  cancelProfileButton: "cancel: Profile Button - Click",
  togglePreviewProfileButton: "toggle: PreviewProfile Button - Click",
  toggleEditProfileButton: "toggle: Edit Profile Button - Click",
  removeEditProfileButton: "remove: Edit Profile Button - Click",
  backEditProfileButton: "back: EditProfile Button - Click",
  submitPromptRatingButton: "submit: Prompt Rating Button - Click",
  submitPhotoRatingButton: "submit: Photo Rating Button - Click",
  matchChoice: "Match Choice",
  submitConversationStarterButton: "submit: ConversationStarter Button - Click",
  closeConversationStarterButton: "close: ConversationStarter Button - Click",
  reportConversationStarterButton: "report: ConversationStarter Button - Click",
  submitReportButton: "submit: Report Button - Click",
  submitScoopFeedbackButton: "submit: ScoopFeedback Button - Click",
  redirectProfileSettingsButton: "redirect: ProfileSettings Button - Click",
  redirectPrivacyButton: "redirect: Privacy Button - Click",
  redirectTermsButton: "redirect: Terms Button - Click",
  deleteAccountButton: "delete: Account Button - Click",
  logoutAccountButton: "logout: Account Button - Click",
  submitFirstImpressionsButton: "submit: FirstImpressions Button - Click",
  selectFirstImpressions: "select: First Impressions",
  getFeedbackLink: "get: Feedback Link - Click",
};

export const methods = {
  scoopLogin: "scoopLogin",
  scoopSignup: "scoopSignup",
};
