export const actions = {
  view: "view",
  save: "save",
  edit: "edit",
  delete: "delete",
};

export const analyticScreenNames = {
  welcome: "Welcome",
  signIn: "Sign In",
  signUp: "Sign up",
  signUpOTP: "Sign Up OTP",
  forgetPassword: "Forgot Password",
  forgotPasswordOTP: "Forgot Password OTP",
  resetPassword: "Reset Password",
  forceAppUpdate: "Force App Update",
  onBoardName: "On Board Name",
  onBoardBirthday: "On Board Birthday",
  onBoardNotification: "On Board Notification",
  onBoardLocation: "On Board Location",
  onBoardGender: "On Board Gender",
  onBoardGenderPreference: "On Board Gender Preference",
  onBoardHeight: "On Board Height",
  onBoardPhotos: "On Board Photos",
  onBoardSelectPrompt: "On Board Select Prompt",
  onBoardSelectPromptList: "On Board Select Prompt List",
  onBoardWritePrompt: "On Board Write Prompt",
  onBoardPrompts: "On Board Prompts",
  openingMessage: "Opening Message",
  ratePromptMessage: "Rate Prompt Message",
  ratePromptExample: "Rate Prompt Example",
  ratePhotoMessage: "Rate Photo Message",
  ratePhotoExample: "Rate Photo Example",
  ratePrompt: "Rate Prompt",
  ratePhoto: "Rate Photo",
  profileView: "Profile View",
  startConversation: "Start Conversation",
  matchMade: "Match Made",
  noMore: "No More",
  blockOrReportUser: "Block or Report User",
  scoopFeedback: "Scoop Feedback",
  main: "Main",
  editProfile: "Edit Profile",
  editPhoto: "Edit Photo",
  photoPromptList: "Photo Prompt List",
  selectPhotoPrompt: "Select Photo Prompt",
  preview: "Preview",
  height: "Height",
  gender: "Gender",
  location: "Location",
  jobTitle: "Job Title",
  company: "Company",
  homeTown: "Home Town",
  school: "School",
  educationLevel: "Education Level",
  ethnicity: "Ethnicity",
  sports: "Sports",
  smoking: "Smoking",
  cannabis: "Cannabis",
  alcohol: "Alcohol",
  drugs: "Drugs",
  diet: "Diet",
  languages: "Languages",
  musicGenre: "Music Genre",
  creativeOulet: "Creative Oulet",
  religion: "Religion",
  religiousPractice: "Religious Practice",
  zodiac: "Zodiac",
  meyerBriggs: "Meyer Briggs",
  characteristics: "Characteristics",
  politics: "politics",
  parentingGoal: "Parenting Goal",
  relationshipGoals: "Relationship Goals",
  relationshipTypes: "Relationship Types",
  pets: "Pets",
  chatList: "Chat List",
  message: "Message",
  profile: "profile",
  aboutMe: "about me",
  vote: "vote",
  visuals: "visuals",
  prompts: "Prompts",
  onBoarding: "onBoarding",
  chat: "conversations",
  messages: "messages",
  matches: "matches",
  launch: "launch",
  viewProfile: "viewProfile",
};

export const screenClass = {
  auth: "Auth",
  appUpdate: "App Update",
  onBoarding: "On Boarding",
  tutorial: "Tutorial",
  matches: "Daily Matches",
  block: "Block",
  feedback: "Feedback",
  profile: "Profile",
  preferences: "Preferences",
  chat: "Chat",
  settings: "Settings",
};

export const eventNames = {
  redirectSignUpButton: "redirectSignUpButton",
  redirectSignInButton: "redirectSignInButton",
  submitSignUpButtonClick: "submitSignUpButtonClick",
  submitSignUpButtonResponse: "submitSignUpButtonResponse",
  submitOtpButton: "submitOtpButton",
  submitResendOtpButton: "submitResendOtpButton",
  submitSignInButtonClick: "submitSignInButtonClick",
  submitSignInButtonResponse: "submitSignInButtonResponse",
  submitForgotPasswordButton: "submitForgotPasswordButton",
  submitOnBoardNameButton: "submitOnBoardNameButton",
  submitOnBoardBirthdayButton: "submitOnBoardBirthdayButton",
  confirmOnBoardBirthdayButton: "confirmOnBoardBirthdayButton",
  dontAllowOnBoardNotificationButton: "dontAllowOnBoardNotificationButton",
  allowOnBoardNotificationButton: "allowOnBoardNotificationButton",
  nextOnBoardNotificationButton: "nextOnBoardNotificationButton",
  submitOnBoardLocationButton: "submitOnBoardLocationButton",
  submitOnBoardGenderButton: "submitOnBoardGenderButton",
  submitOnBoardGenderPreferenceButton: "submitOnBoardGenderPreferenceButton",
  submitOnBoardHeightButton: "submitOnBoardHeightButton",
  addOnBoardPhotosButton: "addOnBoardPhotosButton",
  editOnBoardPhotosButton: "editOnBoardPhotosButton",
  removeOnBoardPhotosButton: "removeOnBoardPhotosButton",
  navigateProfileButton: "navigateProfileButton",
  navigateChatButton: "navigateChatButton",
  navigateRateButton: "navigateRateButton",
  editMainProfileButton: "editMainProfileButton",
  saveProfileButton: "saveProfileButton",
  cancelProfileButton: "cancelProfileButton",
  togglePreviewProfileButton: "togglePreviewProfileButton",
  toggleEditProfileButton: "toggleEditProfileButton",
  removeEditProfileButton: "removeEditProfileButton",
  backEditProfileButton: "backEditProfileButton",
  submitPromptRatingButton: "submitPromptRatingButton",
  submitPhotoRatingButton: "submitPhotoRatingButton",
  declineMatchButton: "declineMatchButton",
  acceptMatchButton: "acceptMatchButton",
  submitConversationStarterButton: "submitConversationStarterButton",
  closeConversationStarterButton: "closeConversationStarterButton",
  reportConversationStarterButton: "reportConversationStarterButton",
  submitReportButton: "submitReportButton",
  submitScoopFeedbackButton: "submitScoopFeedbackButton",
  redirectProfileSettingsButton: "redirectProfileSettingsButton",
  redirectPrivacyButton: "redirectPrivacyButton",
  redirectTermsButton: "redirectTermsButton",
  deleteAccountButton: "deleteAccountButton",
  logoutAccountButton: "logoutAccountButton",
};

export const methods = {
  scoopLogin: "scoopLogin",
  scoopSignup: "scoopSignup",
};
