import { Tag, TagsById, TagsByName } from "./globals";

export const TagInitialData = {
  id: "",
  name: "",
  type: "",
  order: null,
  visible: true,
  emoji: "",
};

export const PHYSICAL_ACTIVITY = [
  {
    id: "1",
    type: "physical_activity",
    name: "archery",
    visible: true,
    emoji: "🏹",
  },
  {
    id: "2",
    type: "physical_activity",
    name: "badminton",
    visible: true,
    emoji: "🏸",
  },
  {
    id: "3",
    type: "physical_activity",
    name: "baseball",
    visible: true,
    emoji: "⚾",
  },
  {
    id: "4",
    type: "physical_activity",
    name: "basketball",
    visible: true,
    emoji: "🏀",
  },
  {
    id: "5",
    type: "physical_activity",
    name: "bowling",
    visible: true,
    emoji: "🎳",
  },
  {
    id: "6",
    type: "physical_activity",
    name: "boxing",
    visible: true,
    emoji: "🥊",
  },
  {
    id: "7",
    type: "physical_activity",
    name: "cricket",
    visible: true,
    emoji: "🏏",
  },
  {
    id: "8",
    type: "physical_activity",
    name: "curling",
    visible: true,
    emoji: "🥌",
  },
  {
    id: "9",
    type: "physical_activity",
    name: "cycling",
    visible: true,
    emoji: "🚴",
  },
  {
    id: "10",
    type: "physical_activity",
    name: "dancing",
    visible: true,
    emoji: "💃🏻",
  },
  {
    id: "11",
    type: "physical_activity",
    name: "darts",
    visible: true,
    emoji: "🎯",
  },
  {
    id: "12",
    type: "physical_activity",
    name: "fencing",
    visible: true,
    emoji: "🤺",
  },
  {
    id: "13",
    type: "physical_activity",
    name: "figure skating",
    visible: true,
    emoji: "⛸️",
  },
  {
    id: "14",
    type: "physical_activity",
    name: "fishing",
    visible: true,
    emoji: "🎣",
  },
  {
    id: "15",
    type: "physical_activity",
    name: "football",
    visible: true,
    emoji: "🏈",
  },
  {
    id: "16",
    type: "physical_activity",
    name: "golf",
    visible: true,
    emoji: "🏌️‍♂️",
  },
  {
    id: "17",
    type: "physical_activity",
    name: "gymnastics",
    visible: true,
    emoji: "🤸",
  },
  {
    id: "18",
    type: "physical_activity",
    name: "hang gliding",
    visible: true,
    emoji: "🪂",
  },
  {
    id: "19",
    type: "physical_activity",
    name: "horse riding",
    visible: true,
    emoji: "🏇",
  },
  {
    id: "20",
    type: "physical_activity",
    name: "ice hockey",
    visible: true,
    emoji: "🏒",
  },
  {
    id: "21",
    type: "physical_activity",
    name: "ice skating",
    visible: true,
    emoji: "⛸️",
  },
  {
    id: "22",
    type: "physical_activity",
    name: "jet skiing",
    visible: true,
    emoji: "🚤",
  },
  {
    id: "23",
    type: "physical_activity",
    name: "judo",
    visible: true,
    emoji: "🥋",
  },
  {
    id: "24",
    type: "physical_activity",
    name: "karate",
    visible: true,
    emoji: "🥋",
  },
  {
    id: "25",
    type: "physical_activity",
    name: "kickboxing",
    visible: true,
    emoji: "🥋",
  },
  {
    id: "26",
    type: "physical_activity",
    name: "lacrosse",
    visible: true,
    emoji: "🥍",
  },
  {
    id: "27",
    type: "physical_activity",
    name: "pool",
    visible: true,
    emoji: "🎱",
  },
  {
    id: "28",
    type: "physical_activity",
    name: "rock climbing",
    visible: true,
    emoji: "🧗",
  },
  {
    id: "29",
    type: "physical_activity",
    name: "roller skating",
    visible: true,
    emoji: "🛼",
  },
  {
    id: "30",
    type: "physical_activity",
    name: "rowing",
    visible: true,
    emoji: "🚣",
  },
  {
    id: "31",
    type: "physical_activity",
    name: "rugby",
    visible: true,
    emoji: "🏉",
  },
  {
    id: "32",
    type: "physical_activity",
    name: "running",
    visible: true,
    emoji: "👟",
  },
  {
    id: "33",
    type: "physical_activity",
    name: "sailing",
    visible: true,
    emoji: "⛵",
  },
  {
    id: "34",
    type: "physical_activity",
    name: "scuba diving",
    visible: true,
    emoji: "🤿",
  },
  {
    id: "35",
    type: "physical_activity",
    name: "skateboarding",
    visible: true,
    emoji: "🛹",
  },
  {
    id: "36",
    type: "physical_activity",
    name: "skiing",
    visible: true,
    emoji: "⛷️",
  },
  {
    id: "37",
    type: "physical_activity",
    name: "sky diving",
    visible: true,
    emoji: "🪂",
  },
  {
    id: "38",
    type: "physical_activity",
    name: "snowboarding",
    visible: true,
    emoji: "🏂🏾",
  },
  {
    id: "39",
    type: "physical_activity",
    name: "soccer",
    visible: true,
    emoji: "⚽",
  },
  {
    id: "40",
    type: "physical_activity",
    name: "surfing",
    visible: true,
    emoji: "🏄",
  },
  {
    id: "41",
    type: "physical_activity",
    name: "swimming",
    visible: true,
    emoji: "🏊‍♀️",
  },
  {
    id: "42",
    type: "physical_activity",
    name: "table tennis",
    visible: true,
    emoji: "🏓",
  },
  {
    id: "43",
    type: "physical_activity",
    name: "taekwondo",
    visible: true,
    emoji: "🥋",
  },
  {
    id: "44",
    type: "physical_activity",
    name: "tennis",
    visible: true,
    emoji: "🎾",
  },
  {
    id: "45",
    type: "physical_activity",
    name: "volleyball",
    visible: true,
    emoji: "🏐",
  },
  {
    id: "46",
    type: "physical_activity",
    name: "water skiing",
    visible: true,
    emoji: "💦🎿",
  },
  {
    id: "47",
    type: "physical_activity",
    name: "weight lifting",
    visible: true,
    emoji: "🏋️",
  },
  {
    id: "48",
    type: "physical_activity",
    name: "wind surfing",
    visible: true,
    emoji: "💨🏄",
  },
  {
    id: "49",
    type: "physical_activity",
    name: "wrestling",
    visible: true,
    emoji: "🤼‍♂️",
  },
  {
    id: "50",
    type: "physical_activity",
    name: "yoga",
    visible: true,
    emoji: "🧘‍♀️",
  },
];

export const PHYSICAL_ACTIVITY_FREQUENCY = [
  {
    id: "51",
    type: "physical_activity_frequency",
    name: "Daily",
    order: 1,
    visible: true,
    emoji: "📅",
  },
  {
    id: "52",
    type: "physical_activity_frequency",
    name: "Almost Daily",
    order: 2,
    visible: true,
    emoji: "📅",
  },
  {
    id: "53",
    type: "physical_activity_frequency",
    name: "Weekly",
    order: 3,
    visible: true,
    emoji: "📅",
  },
  {
    id: "54",
    type: "physical_activity_frequency",
    name: "Monthly",
    order: 4,
    visible: true,
    emoji: "📅",
  },
  {
    id: "55",
    type: "physical_activity_frequency",
    name: "Almost never",
    order: 5,
    visible: true,
    emoji: "📅",
  },
];

export const ZODIAC_SIGNS = [
  {
    id: "56",
    type: "zodiac",
    name: "Aries",
    order: 1,
    visible: true,
    emoji: "♈",
  },
  {
    id: "57",
    type: "zodiac",
    name: "Taurus",
    order: 2,
    visible: true,
    emoji: "♉",
  },
  {
    id: "58",
    type: "zodiac",
    name: "Gemini",
    order: 3,
    visible: true,
    emoji: "♊",
  },
  {
    id: "59",
    type: "zodiac",
    name: "Cancer",
    order: 4,
    visible: true,
    emoji: "♋",
  },
  { id: "60", type: "zodiac", name: "Leo", order: 5, visible: true, emoji: "♌" },
  {
    id: "61",
    type: "zodiac",
    name: "Virgo",
    order: 6,
    visible: true,
    emoji: "♍",
  },
  {
    id: "62",
    type: "zodiac",
    name: "Libra",
    order: 7,
    visible: true,
    emoji: "♎",
  },
  {
    id: "63",
    type: "zodiac",
    name: "Scorpio",
    order: 8,
    visible: true,
    emoji: "♏",
  },
  {
    id: "64",
    type: "zodiac",
    name: "Sagittarius",
    order: 9,
    visible: true,
    emoji: "♐",
  },
  {
    id: "65",
    type: "zodiac",
    name: "Capricorn",
    order: 10,
    visible: true,
    emoji: "♑",
  },
  {
    id: "66",
    type: "zodiac",
    name: "Aquarius",
    order: 11,
    visible: true,
    emoji: "♒",
  },
  {
    id: "67",
    type: "zodiac",
    name: "Pisces",
    order: 12,
    visible: true,
    emoji: "♓",
  },
];

export const EDUCATION_LEVEL = [
  {
    id: "68",
    type: "education",
    name: "High School",
    order: 1,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "69",
    type: "education",
    name: "Bachelors",
    order: 2,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "70",
    type: "education",
    name: "Masters",
    order: 3,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "71",
    type: "education",
    name: "MBA",
    order: 4,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "72",
    type: "education",
    name: "PhD",
    order: 5,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "73",
    type: "education",
    name: "MD",
    order: 6,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "74",
    type: "education",
    name: "Doctor of Education (EdD)",
    order: 7,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "75",
    type: "education",
    name: "JD",
    order: 8,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "76",
    type: "education",
    name: "Doctor of Osteopathic (DO)",
    order: 9,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "77",
    type: "education",
    name: "Doctor of Veterinary Medicine (DVM)",
    order: 10,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "78",
    type: "education",
    name: "Doctor of Dental Medicine (DMD)",
    order: 11,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "79",
    type: "education",
    name: "Doctor of Dental Surgery (DDS)",
    order: 12,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "80",
    type: "education",
    name: "Associate Degree",
    order: 13,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "81",
    type: "education",
    name: "Cosmetic License",
    order: 14,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "82",
    type: "education",
    name: "Massage Therapy Diploma",
    order: 15,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "83",
    type: "education",
    name: "Aesthetician License",
    order: 16,
    visible: true,
    emoji: "🎓",
  },
  {
    id: "84",
    type: "education",
    name: "Paralegal Certificate",
    order: 17,
    visible: true,
    emoji: "🎓",
  },
];

export const ETHNICITY = [
  { id: "85", type: "ethnicity", name: "Asian", visible: true, emoji: "🌎" },
  { id: "86", type: "ethnicity", name: "Arab", visible: true, emoji: "🌎" },
  {
    id: "87",
    type: "ethnicity",
    name: "Black/African-descent",
    visible: true,
    emoji: "🌎",
  },
  {
    id: "88",
    type: "ethnicity",
    name: "Hispanic/Latino",
    visible: true,
    emoji: "🌎",
  },
  {
    id: "89",
    type: "ethnicity",
    name: "Native American",
    visible: true,
    emoji: "🌎",
  },
  {
    id: "90",
    type: "ethnicity",
    name: "Pacific Islander",
    visible: true,
    emoji: "🌎",
  },
  {
    id: "91",
    type: "ethnicity",
    name: "South Asian",
    visible: true,
    emoji: "🌎",
  },
  {
    id: "92",
    type: "ethnicity",
    name: "White/Caucasian",
    visible: true,
    emoji: "🌎",
  },
];

export const RELIGION = [
  { id: "93", type: "religion", name: "Agnostic", visible: true, emoji: "🤔" },
  { id: "94", type: "religion", name: "Atheist", visible: true, emoji: "🚫⛪" },
  { id: "95", type: "religion", name: "Buddhist", visible: true, emoji: "🪬" },
  { id: "96", type: "religion", name: "Catholic", visible: true, emoji: "⛪" },
  { id: "97", type: "religion", name: "Christian", visible: true, emoji: "⛪" },
  { id: "98", type: "religion", name: "Hindu", visible: true, emoji: "🕉" },
  { id: "99", type: "religion", name: "Jewish", visible: true, emoji: "✡️" },
  { id: "100", type: "religion", name: "Mormon", visible: true, emoji: "📘" },
  { id: "101", type: "religion", name: "Muslim", visible: true, emoji: "🕌" },
  { id: "102", type: "religion", name: "Shinto", visible: true, emoji: "⛩️" },
  { id: "103", type: "religion", name: "Sikh", visible: true, emoji: "🔵" },
  { id: "104", type: "religion", name: "Spiritual", visible: true, emoji: "🌌" },
  {
    id: "105",
    type: "religion",
    name: "Zoroastrian",
    visible: true,
    emoji: "🔥",
  },
];

export const RELIGIOUS_PRACTICES = [
  {
    id: "106",
    type: "religious_practice",
    name: "not practicing",
    order: 1,
    visible: true,
    emoji: "",
  },
  {
    id: "107",
    type: "religious_practice",
    name: "in faith / in belief",
    order: 2,
    visible: true,
    emoji: "",
  },
  {
    id: "108",
    type: "religious_practice",
    name: "practicing when with family",
    order: 3,
    visible: true,
    emoji: "",
  },
  {
    id: "109",
    type: "religious_practice",
    name: "moderate practice",
    order: 4,
    visible: true,
    emoji: "",
  },
  {
    id: "110",
    type: "religious_practice",
    name: "active practice",
    order: 5,
    visible: true,
    emoji: "",
  },
];

export const DRUG_USAGE = [
  {
    id: "111",
    type: "drug_usage",
    name: "Never",
    order: 1,
    visible: true,
    emoji: "🚫💊",
  },
  {
    id: "112",
    type: "drug_usage",
    name: "Socially",
    order: 2,
    visible: true,
    emoji: "💊",
  },
  {
    id: "113",
    type: "drug_usage",
    name: "Regularly",
    order: 3,
    visible: true,
    emoji: "💊",
  },
  {
    id: "114",
    type: "drug_usage",
    name: "Medicinally",
    order: 4,
    visible: true,
    emoji: "💊",
  },
];

export const CANNABIS_USAGE = [
  {
    id: "115",
    type: "cannibis_usage",
    name: "Never",
    order: 1,
    visible: true,
    emoji: "🚫🌿",
  },
  {
    id: "116",
    type: "cannibis_usage",
    name: "Socially",
    order: 2,
    visible: true,
    emoji: "🌿",
  },
  {
    id: "117",
    type: "cannibis_usage",
    name: "Regularly",
    order: 3,
    visible: true,
    emoji: "🌿",
  },
  {
    id: "118",
    type: "cannibis_usage",
    name: "Medicinally",
    order: 4,
    visible: true,
    emoji: "🌿",
  },
];

export const RELATIONSHIP_TYPE = [
  {
    id: "119",
    type: "relationship_type",
    name: "Monogomy",
    visible: true,
    emoji: "❤️",
  },
  {
    id: "120",
    type: "relationship_type",
    name: "Non-Monogamy",
    visible: true,
    emoji: "❤️",
  },
  {
    id: "121",
    type: "relationship_type",
    name: "Monogamish",
    visible: true,
    emoji: "❤️",
  },
  {
    id: "122",
    type: "relationship_type",
    name: "Polygamy",
    visible: true,
    emoji: "❤️",
  },
  {
    id: "123",
    type: "relationship_type",
    name: "Open",
    visible: true,
    emoji: "❤️",
  },
  {
    id: "124",
    type: "relationship_type",
    name: "Swinging",
    visible: true,
    emoji: "❤️",
  },
  {
    id: "125",
    type: "relationship_type",
    name: "Polyamory",
    visible: true,
    emoji: "❤️",
  },
  {
    id: "126",
    type: "relationship_type",
    name: "Polyfidelity",
    visible: true,
    emoji: "❤️",
  },
  {
    id: "127",
    type: "relationship_type",
    name: "Polyaffective",
    visible: true,
    emoji: "❤️",
  },
  {
    id: "128",
    type: "relationship_type",
    name: "Don't Know",
    visible: true,
    emoji: "❤️",
  },
  {
    id: "129",
    type: "relationship_type",
    name: "Open to trying",
    visible: true,
    emoji: "❤️",
  },
];

export const RELATIONSHIP_GOALS = [
  {
    id: "130",
    type: "relationship_goal",
    name: "Marriage",
    visible: true,
    emoji: "❤️",
  },
  {
    id: "131",
    type: "relationship_goal",
    name: "Something Casual",
    visible: true,
    emoji: "❤️",
  },
  {
    id: "132",
    type: "relationship_goal",
    name: "Friendship",
    visible: true,
    emoji: "❤️",
  },
  {
    id: "133",
    type: "relationship_goal",
    name: "Don't know yet",
    visible: true,
    emoji: "❤️",
  },
  {
    id: "134",
    type: "relationship_goal",
    name: "Relationship",
    visible: true,
    emoji: "❤️",
  },
];

export const PARENTING_GOALS = [
  {
    id: "135",
    type: "parenting_goal",
    name: "Want someday",
    visible: true,
    emoji: "👶",
  },
  {
    id: "136",
    type: "parenting_goal",
    name: "Don't want",
    visible: true,
    emoji: "🚫👶",
  },
  {
    id: "137",
    type: "parenting_goal",
    name: "Undecided",
    visible: true,
    emoji: "",
  },
  {
    id: "138",
    type: "parenting_goal",
    name: "Indifferent",
    visible: true,
    emoji: "",
  },
  { id: "139", type: "parenting_goal", name: "Have", visible: true, emoji: "👶" },
  {
    id: "140",
    type: "parenting_goal",
    name: "Have and want more",
    visible: true,
    emoji: "👶",
  },
  {
    id: "141",
    type: "parenting_goal",
    name: "Have and don't want more",
    visible: true,
    emoji: "👶",
  },
  {
    id: "142",
    type: "parenting_goal",
    name: "Have and undecided to more",
    visible: true,
    emoji: "👶",
  },
  {
    id: "143",
    type: "parenting_goal",
    name: "Have and open to more",
    visible: true,
    emoji: "👶",
  },
];

export const POLITICS = [
  { id: "144", type: "politics", name: "Apolitical", visible: true, emoji: "🤷" },
  { id: "145", type: "politics", name: "Moderate", visible: true, emoji: "⚖️" },
  { id: "146", type: "politics", name: "Liberal", visible: true, emoji: "🕊️" },
  {
    id: "147",
    type: "politics",
    name: "Conservative",
    visible: true,
    emoji: "🐘",
  },
];

export const CREATIVE = [
  { id: "148", type: "creative", name: "Acting", visible: true, emoji: "🎬" },
  { id: "149", type: "creative", name: "Art", visible: true, emoji: "🎨" },
  { id: "150", type: "creative", name: "Baking", visible: true, emoji: "🍰" },
  { id: "151", type: "creative", name: "Blogging", visible: true, emoji: "👨‍💻" },
  { id: "152", type: "creative", name: "Carpentry", visible: true, emoji: "🪚" },
  { id: "153", type: "creative", name: "Coding", visible: true, emoji: "👩‍💻" },
  { id: "154", type: "creative", name: "Comedy", visible: true, emoji: "🎭" },
  { id: "155", type: "creative", name: "Cooking", visible: true, emoji: "🧑‍🍳" },
  { id: "156", type: "creative", name: "Crafts", visible: true, emoji: "✂️" },
  { id: "157", type: "creative", name: "Dancing", visible: true, emoji: "💃🏻" },
  { id: "158", type: "creative", name: "Design", visible: true, emoji: "👜" },
  { id: "159", type: "creative", name: "Fashion", visible: true, emoji: "👠" },
  { id: "160", type: "creative", name: "Gardening", visible: true, emoji: "🪴" },
  {
    id: "161",
    type: "creative",
    name: "Interior / Exterior Renovations",
    visible: true,
    emoji: "🔨",
  },
  { id: "162", type: "creative", name: "Make-up", visible: true, emoji: "💄" },
  {
    id: "163",
    type: "creative",
    name: "Making / Writing music",
    visible: true,
    emoji: "🎶",
  },
  {
    id: "164",
    type: "creative",
    name: "Making videos",
    visible: true,
    emoji: "🎬",
  },
  { id: "165", type: "creative", name: "Painting", visible: true, emoji: "🎨" },
  {
    id: "166",
    type: "creative",
    name: "Photography",
    visible: true,
    emoji: "📷",
  },
  { id: "167", type: "creative", name: "Pottery", visible: true, emoji: "🫖" },
];

export const GOING_OUT = [
  { id: "171", type: "going_out", name: "Bars", visible: true, emoji: "🍸" },
  { id: "172", type: "going_out", name: "Concerts", visible: true, emoji: "🎵" },
  { id: "173", type: "going_out", name: "Festivals", visible: true, emoji: "🎫" },
  {
    id: "174",
    type: "going_out",
    name: "Museums & galleries",
    visible: true,
    emoji: "🖼️",
  },
  {
    id: "175",
    type: "going_out",
    name: "Nightclubs",
    visible: true,
    emoji: "🎟️",
  },
  { id: "176", type: "going_out", name: "Stand up", visible: true, emoji: "🎭" },
  { id: "177", type: "going_out", name: "Theater", visible: true, emoji: "🎞️" },
];

export const STAYING_IN = [
  { id: "178", type: "staying_in", name: "baking", visible: true, emoji: "🍪" },
  { id: "179", type: "staying_in", name: "cooking", visible: true, emoji: "🍳" },
  {
    id: "180",
    type: "staying_in",
    name: "board games",
    visible: true,
    emoji: "🎲",
  },
  {
    id: "181",
    type: "staying_in",
    name: "gardening",
    visible: true,
    emoji: "👩‍🌾",
  },
  { id: "182", type: "staying_in", name: "takeout", visible: true, emoji: "🥡" },
  {
    id: "183",
    type: "staying_in",
    name: "video games",
    visible: true,
    emoji: "🎮",
  },
  { id: "184", type: "staying_in", name: "movies", visible: true, emoji: "🍿" },
  {
    id: "185",
    type: "staying_in",
    name: "TV series",
    visible: true,
    emoji: "📺",
  },
];

export const FILM_GENRE = [
  {
    id: "186",
    type: "film_genre",
    name: "Action & Adventure",
    visible: true,
    emoji: "🎬",
  },
  { id: "187", type: "film_genre", name: "Animated", visible: true, emoji: "🎞️" },
  { id: "188", type: "film_genre", name: "Anime", visible: true, emoji: "🇯🇵" },
  {
    id: "189",
    type: "film_genre",
    name: "Bollywood",
    visible: true,
    emoji: "🇮🇳",
  },
  { id: "190", type: "film_genre", name: "Comedy", visible: true, emoji: "😂" },
  {
    id: "191",
    type: "film_genre",
    name: "Cooking shows",
    visible: true,
    emoji: "🍳",
  },
  { id: "192", type: "film_genre", name: "Crime", visible: true, emoji: "🚔" },
  {
    id: "193",
    type: "film_genre",
    name: "Documentaries",
    visible: true,
    emoji: "🎥",
  },
  { id: "194", type: "film_genre", name: "Drama", visible: true, emoji: "🎭" },
  { id: "195", type: "film_genre", name: "Fantasy", visible: true, emoji: "🧙" },
  {
    id: "196",
    type: "film_genre",
    name: "Game Shows",
    visible: true,
    emoji: "🎮",
  },
  { id: "197", type: "film_genre", name: "Horror", visible: true, emoji: "👻" },
  { id: "198", type: "film_genre", name: "Indie", visible: true, emoji: "🎨" },
  { id: "199", type: "film_genre", name: "Mystery", visible: true, emoji: "🔍" },
  {
    id: "200",
    type: "film_genre",
    name: "Reality Shows",
    visible: true,
    emoji: "📺",
  },
  { id: "201", type: "film_genre", name: "Rom-com", visible: true, emoji: "💘" },
  { id: "202", type: "film_genre", name: "Romance", visible: true, emoji: "❤️" },
  { id: "203", type: "film_genre", name: "Sci-fi", visible: true, emoji: "👽" },
  {
    id: "204",
    type: "film_genre",
    name: "Superhero",
    visible: true,
    emoji: "🦸",
  },
  { id: "205", type: "film_genre", name: "Thriller", visible: true, emoji: "🧟" },
];

export const BOOK_GENRE = [
  {
    id: "206",
    type: "book_genre",
    name: "Action & Adventure",
    visible: true,
    emoji: "🎬",
  },
  {
    id: "207",
    type: "book_genre",
    name: "Biographies",
    visible: true,
    emoji: "📘",
  },
  { id: "208", type: "book_genre", name: "Classics", visible: true, emoji: "📜" },
  { id: "209", type: "book_genre", name: "Comedy", visible: true, emoji: "😂" },
  {
    id: "210",
    type: "book_genre",
    name: "Comic books",
    visible: true,
    emoji: "📚",
  },
  { id: "211", type: "book_genre", name: "Crime", visible: true, emoji: "🚔" },
  { id: "212", type: "book_genre", name: "Fantasy", visible: true, emoji: "🧙" },
  { id: "213", type: "book_genre", name: "History", visible: true, emoji: "📜" },
  { id: "214", type: "book_genre", name: "Horror", visible: true, emoji: "👻" },
  { id: "215", type: "book_genre", name: "Manga", visible: true, emoji: "🇯🇵" },
  { id: "216", type: "book_genre", name: "Mystery", visible: true, emoji: "🔍" },
  {
    id: "217",
    type: "book_genre",
    name: "Philosophy",
    visible: true,
    emoji: "🤔",
  },
  { id: "218", type: "book_genre", name: "Poetry", visible: true, emoji: "📜" },
  {
    id: "219",
    type: "book_genre",
    name: "Psychology",
    visible: true,
    emoji: "🧠",
  },
  { id: "220", type: "book_genre", name: "Romance", visible: true, emoji: "❤️" },
  { id: "221", type: "book_genre", name: "Sci-fi", visible: true, emoji: "👽" },
  { id: "222", type: "book_genre", name: "Science", visible: true, emoji: "🔬" },
  { id: "223", type: "book_genre", name: "Thriller", visible: true, emoji: "🧟" },
  {
    id: "224",
    type: "book_genre",
    name: "Non-fiction",
    visible: true,
    emoji: "📚",
  },
];

export const MUSIC_GENRE = [
  { id: "225", type: "music_genre", name: "Afro", visible: true, emoji: "🎵" },
  { id: "226", type: "music_genre", name: "Arab", visible: true, emoji: "🐫" },
  { id: "227", type: "music_genre", name: "Blues", visible: true, emoji: "🎵" },
  {
    id: "228",
    type: "music_genre",
    name: "Classical",
    visible: true,
    emoji: "🎻",
  },
  { id: "229", type: "music_genre", name: "Country", visible: true, emoji: "🤠" },
  { id: "230", type: "music_genre", name: "Desi", visible: true, emoji: "🇮🇳" },
  { id: "231", type: "music_genre", name: "EDM", visible: true, emoji: "🎵" },
  {
    id: "232",
    type: "music_genre",
    name: "Electronic",
    visible: true,
    emoji: "🎵",
  },
  {
    id: "233",
    type: "music_genre",
    name: "Folk & Acoustic",
    visible: true,
    emoji: "🎵",
  },
  { id: "234", type: "music_genre", name: "Funk", visible: true, emoji: "🕺" },
  { id: "235", type: "music_genre", name: "Hip Hop", visible: true, emoji: "🎵" },
  { id: "236", type: "music_genre", name: "House", visible: true, emoji: "🏠" },
  { id: "237", type: "music_genre", name: "Indie", visible: true, emoji: "🎵" },
  { id: "238", type: "music_genre", name: "Jazz", visible: true, emoji: "🎵" },
  { id: "239", type: "music_genre", name: "K-pop", visible: true, emoji: "🇰🇷" },
  { id: "240", type: "music_genre", name: "Latin", visible: true, emoji: "💃" },
  { id: "241", type: "music_genre", name: "Metal", visible: true, emoji: "🤘" },
  { id: "242", type: "music_genre", name: "Pop", visible: true, emoji: "🎵" },
  { id: "243", type: "music_genre", name: "Punk", visible: true, emoji: "🎸" },
  { id: "244", type: "music_genre", name: "R&B", visible: true, emoji: "🎵" },
  { id: "245", type: "music_genre", name: "Rap", visible: true, emoji: "🎵" },
  { id: "246", type: "music_genre", name: "Reggae", visible: true, emoji: "🇯🇲" },
  { id: "247", type: "music_genre", name: "Rock", visible: true, emoji: "🎵" },
  { id: "248", type: "music_genre", name: "Soul", visible: true, emoji: "🎵" },
  { id: "249", type: "music_genre", name: "Techno", visible: true, emoji: "🎵" },
];

export const DRINKS = [
  { id: "250", type: "drink", name: "Aperitif", visible: true, emoji: "🍸" },
  { id: "251", type: "drink", name: "Beer", visible: true, emoji: "🍺" },
  { id: "252", type: "drink", name: "Boba tea", visible: true, emoji: "🧋" },
  { id: "253", type: "drink", name: "Cocktails", visible: true, emoji: "🍹" },
  { id: "254", type: "drink", name: "Coffee", visible: true, emoji: "☕" },
  {
    id: "255",
    type: "drink",
    name: "Cold pressed juice",
    visible: true,
    emoji: "🥤",
  },
  { id: "256", type: "drink", name: "Energy Drink", visible: true, emoji: "⚡" },
  { id: "257", type: "drink", name: "Expresso", visible: true, emoji: "☕" },
  { id: "258", type: "drink", name: "Gin", visible: true, emoji: "🍸" },
  { id: "259", type: "drink", name: "Hot chocolate", visible: true, emoji: "🍫" },
  { id: "260", type: "drink", name: "Juice", visible: true, emoji: "🥤" },
  { id: "261", type: "drink", name: "Kombucha", visible: true, emoji: "🍵" },
  {
    id: "262",
    type: "drink",
    name: "Latte / Cappuccino",
    visible: true,
    emoji: "☕",
  },
  { id: "263", type: "drink", name: "Mezcal", visible: true, emoji: "🥃" },
  { id: "264", type: "drink", name: "Pop Soda", visible: true, emoji: "🥤" },
  { id: "265", type: "drink", name: "Protein Shake", visible: true, emoji: "💪" },
  { id: "266", type: "drink", name: "Smoothie", visible: true, emoji: "🥤" },
  {
    id: "267",
    type: "drink",
    name: "Sports Drink / Electrolytes",
    visible: true,
    emoji: "🏋️‍♂️",
  },
  { id: "268", type: "drink", name: "Tea", visible: true, emoji: "🍵" },
  { id: "269", type: "drink", name: "Tequila", visible: true, emoji: "🥃" },
  { id: "270", type: "drink", name: "Whisky", visible: true, emoji: "🥃" },
  { id: "271", type: "drink", name: "Wine", visible: true, emoji: "🍷" },
];

export const DIET = [
  { id: "272", type: "diet", name: "Vegan", visible: true, emoji: "🌱" },
  { id: "273", type: "diet", name: "Vegetarian", visible: true, emoji: "🥦" },
  { id: "274", type: "diet", name: "Gluten Free", visible: true, emoji: "🚫🌾" },
  { id: "275", type: "diet", name: "Halal", visible: true, emoji: "☪️" },
  { id: "276", type: "diet", name: "Pescatarian", visible: true, emoji: "🐟" },
  { id: "277", type: "diet", name: "Paleo", visible: true, emoji: "🥩" },
  { id: "278", type: "diet", name: "Kosher", visible: true, emoji: "✡️" },
  { id: "279", type: "diet", name: "Keto", visible: true, emoji: "🥑" },
  { id: "280", type: "diet", name: "Dairy Free", visible: true, emoji: "🚫🥛" },
  { id: "281", type: "diet", name: "Peanut Free", visible: true, emoji: "🚫🥜" },
  { id: "282", type: "diet", name: "Nut free", visible: true, emoji: "🚫🌰" },
  {
    id: "283",
    type: "diet",
    name: "Intermitent Fasting",
    visible: true,
    emoji: "⏱️",
  },
];

export const TRAVEL_GOALS = [
  {
    id: "284",
    type: "travel_goals",
    name: "Culture & History Trips",
    visible: true,
    emoji: "🏛️",
  },
  {
    id: "285",
    type: "travel_goals",
    name: "Outdoor Adventure",
    visible: true,
    emoji: "🏞️",
  },
  {
    id: "286",
    type: "travel_goals",
    name: "Relaxation & Wellness",
    visible: true,
    emoji: "💆🏻‍♀️",
  },
  {
    id: "287",
    type: "travel_goals",
    name: "Foodie Trips",
    visible: true,
    emoji: "🍽️",
  },
  {
    id: "288",
    type: "travel_goals",
    name: "Creative Experiences",
    visible: true,
    emoji: "🎨",
  },
  {
    id: "289",
    type: "travel_goals",
    name: "Photography & Content Creation",
    visible: true,
    emoji: "📸",
  },
  {
    id: "290",
    type: "travel_goals",
    name: "Shopping",
    visible: true,
    emoji: "🛍️",
  },
  {
    id: "291",
    type: "travel_goals",
    name: "Volunteering & Community",
    visible: true,
    emoji: "🤝",
  },
  {
    id: "292",
    type: "travel_goals",
    name: "Road Trips",
    visible: true,
    emoji: "🚗",
  },
  {
    id: "293",
    type: "travel_goals",
    name: "Staycation",
    visible: true,
    emoji: "🏠",
  },
  {
    id: "294",
    type: "travel_goals",
    name: "Visiting Friends & Family Time",
    visible: true,
    emoji: "👨‍👩‍👧‍👦",
  },
  {
    id: "295",
    type: "travel_goals",
    name: "Festivals",
    visible: true,
    emoji: "🎉",
  },
  {
    id: "296",
    type: "travel_goals",
    name: "Spiritual Journeys & Mindfulness",
    visible: true,
    emoji: "🧘‍♂️",
  },
  {
    id: "297",
    type: "travel_goals",
    name: "City breaks",
    visible: true,
    emoji: "🌆",
  },
];

export const PETS = [
  { id: "298", type: "pets", name: "Bird", visible: true, emoji: "🐦" },
  { id: "299", type: "pets", name: "Cat", visible: true, emoji: "🐱" },
  { id: "300", type: "pets", name: "Crustacean", visible: true, emoji: "🐌" },
  { id: "301", type: "pets", name: "Dog", visible: true, emoji: "🐶" },
  {
    id: "302",
    type: "pets",
    name: "Ferret / Weasel",
    visible: true,
    emoji: "🦡",
  },
  { id: "303", type: "pets", name: "Fish", visible: true, emoji: "🐠" },
  { id: "304", type: "pets", name: "Goat", visible: true, emoji: "🐐" },
  { id: "305", type: "pets", name: "Guinea Pig", visible: true, emoji: "🐹" },
  { id: "306", type: "pets", name: "Hamster", visible: true, emoji: "🐹" },
  { id: "307", type: "pets", name: "Hedgehog", visible: true, emoji: "🦔" },
  { id: "308", type: "pets", name: "Horse", visible: true, emoji: "🐴" },
  { id: "309", type: "pets", name: "Insect", visible: true, emoji: "🐛" },
  { id: "310", type: "pets", name: "Mouse", visible: true, emoji: "🐭" },
  { id: "311", type: "pets", name: "Pig", visible: true, emoji: "🐷" },
  { id: "312", type: "pets", name: "Rabbit", visible: true, emoji: "🐰" },
  { id: "313", type: "pets", name: "Reptile", visible: true, emoji: "🐸" },
  { id: "314", type: "pets", name: "Sheep", visible: true, emoji: "🐑" },
];

export const DATE_OPTIONS = [
  { id: "315", type: "date_options", name: "Men", visible: true, emoji: "♂️" },
  { id: "316", type: "date_options", name: "Women", visible: true, emoji: "♀️" },
  { id: "317", type: "date_options", name: "Both", visible: true, emoji: "♂️♀️" },
];

export const GENDERS = [
  { id: "318", type: "gender", name: "Man", visible: true, emoji: "♂️" },
  { id: "319", type: "gender", name: "Woman", visible: true, emoji: "♀️" },
];

export const LANGUAGES = [
  { id: "320", type: "language", name: "Afrikaans", visible: true, emoji: "💬" },
  { id: "321", type: "language", name: "Albanian", visible: true, emoji: "💬" },
  { id: "322", type: "language", name: "Amharic", visible: true, emoji: "💬" },
  { id: "323", type: "language", name: "Arabic", visible: true, emoji: "💬" },
  { id: "324", type: "language", name: "Aramaic", visible: true, emoji: "💬" },
  { id: "325", type: "language", name: "Armenian", visible: true, emoji: "💬" },
  { id: "326", type: "language", name: "Assamese", visible: true, emoji: "💬" },
  { id: "327", type: "language", name: "Aymara", visible: true, emoji: "💬" },
  {
    id: "328",
    type: "language",
    name: "Azerbaijani",
    visible: true,
    emoji: "💬",
  },
  { id: "329", type: "language", name: "Balochi", visible: true, emoji: "💬" },
  { id: "330", type: "language", name: "Bamanankan", visible: true, emoji: "💬" },
  {
    id: "331",
    type: "language",
    name: "Bashkort (Bashkir)",
    visible: true,
    emoji: "💬",
  },
  { id: "332", type: "language", name: "Basque", visible: true, emoji: "💬" },
  { id: "333", type: "language", name: "Belarusan", visible: true, emoji: "💬" },
  { id: "334", type: "language", name: "Bengali", visible: true, emoji: "💬" },
  { id: "335", type: "language", name: "Bhojpuri", visible: true, emoji: "💬" },
  { id: "336", type: "language", name: "Bislama", visible: true, emoji: "💬" },
  { id: "337", type: "language", name: "Bosnian", visible: true, emoji: "💬" },
  { id: "338", type: "language", name: "Brahui", visible: true, emoji: "💬" },
  { id: "339", type: "language", name: "Bulgarian", visible: true, emoji: "💬" },
  { id: "340", type: "language", name: "Burmese", visible: true, emoji: "💬" },
  { id: "341", type: "language", name: "Cantonese", visible: true, emoji: "💬" },
  { id: "342", type: "language", name: "Catalan", visible: true, emoji: "💬" },
  { id: "343", type: "language", name: "Cebuano", visible: true, emoji: "💬" },
  { id: "344", type: "language", name: "Chechen", visible: true, emoji: "💬" },
  { id: "345", type: "language", name: "Cherokee", visible: true, emoji: "💬" },
  { id: "346", type: "language", name: "Croatian", visible: true, emoji: "💬" },
  { id: "347", type: "language", name: "Czech", visible: true, emoji: "💬" },
  { id: "348", type: "language", name: "Dakota", visible: true, emoji: "💬" },
  { id: "349", type: "language", name: "Danish", visible: true, emoji: "💬" },
  { id: "350", type: "language", name: "Dari", visible: true, emoji: "💬" },
  { id: "351", type: "language", name: "Dholuo", visible: true, emoji: "💬" },
  { id: "352", type: "language", name: "Dutch", visible: true, emoji: "💬" },
  { id: "353", type: "language", name: "English", visible: true, emoji: "💬" },
  { id: "354", type: "language", name: "Esperanto", visible: true, emoji: "💬" },
  { id: "355", type: "language", name: "Estonian", visible: true, emoji: "💬" },
  { id: "356", type: "language", name: "Éwé", visible: true, emoji: "💬" },
  { id: "357", type: "language", name: "Finnish", visible: true, emoji: "💬" },
  { id: "358", type: "language", name: "French", visible: true, emoji: "💬" },
  { id: "359", type: "language", name: "Georgian", visible: true, emoji: "💬" },
  { id: "360", type: "language", name: "German", visible: true, emoji: "💬" },
  { id: "361", type: "language", name: "Gikuyu", visible: true, emoji: "💬" },
  { id: "362", type: "language", name: "Greek", visible: true, emoji: "💬" },
  { id: "363", type: "language", name: "Guarani", visible: true, emoji: "💬" },
  { id: "364", type: "language", name: "Gujarati", visible: true, emoji: "💬" },
  {
    id: "365",
    type: "language",
    name: "Haitian Creole",
    visible: true,
    emoji: "💬",
  },
  { id: "366", type: "language", name: "Hausa", visible: true, emoji: "💬" },
  { id: "367", type: "language", name: "Hawaiian", visible: true, emoji: "💬" },
  {
    id: "368",
    type: "language",
    name: "Hawaiian Creole",
    visible: true,
    emoji: "💬",
  },
  { id: "369", type: "language", name: "Hebrew", visible: true, emoji: "💬" },
  { id: "370", type: "language", name: "Hiligaynon", visible: true, emoji: "💬" },
  { id: "371", type: "language", name: "Hindi", visible: true, emoji: "💬" },
  { id: "372", type: "language", name: "Hungarian", visible: true, emoji: "💬" },
  { id: "373", type: "language", name: "Icelandic", visible: true, emoji: "💬" },
  { id: "374", type: "language", name: "Igbo", visible: true, emoji: "💬" },
  { id: "375", type: "language", name: "Ilocano", visible: true, emoji: "💬" },
  { id: "376", type: "language", name: "Indonesian", visible: true, emoji: "💬" },
  {
    id: "377",
    type: "language",
    name: "Inuit/Inupiaq",
    visible: true,
    emoji: "💬",
  },
  {
    id: "378",
    type: "language",
    name: "Irish Gaelic",
    visible: true,
    emoji: "💬",
  },
  { id: "379", type: "language", name: "Italian", visible: true, emoji: "💬" },
  { id: "380", type: "language", name: "Japanese", visible: true, emoji: "💬" },
  { id: "381", type: "language", name: "Jarai", visible: true, emoji: "💬" },
  { id: "382", type: "language", name: "Javanese", visible: true, emoji: "💬" },
  { id: "383", type: "language", name: "K’iche’", visible: true, emoji: "💬" },
  { id: "384", type: "language", name: "Kabyle", visible: true, emoji: "💬" },
  { id: "385", type: "language", name: "Kannada", visible: true, emoji: "💬" },
  { id: "386", type: "language", name: "Kashmiri", visible: true, emoji: "💬" },
  { id: "387", type: "language", name: "Kazakh", visible: true, emoji: "💬" },
  { id: "388", type: "language", name: "Khmer", visible: true, emoji: "💬" },
  { id: "389", type: "language", name: "Khoekhoe", visible: true, emoji: "💬" },
  { id: "390", type: "language", name: "Korean", visible: true, emoji: "💬" },
  { id: "391", type: "language", name: "Kurdish", visible: true, emoji: "💬" },
  { id: "392", type: "language", name: "Kyrgyz", visible: true, emoji: "💬" },
  { id: "393", type: "language", name: "Lao", visible: true, emoji: "💬" },
  { id: "394", type: "language", name: "Latin", visible: true, emoji: "💬" },
  { id: "395", type: "language", name: "Latvian", visible: true, emoji: "💬" },
  { id: "396", type: "language", name: "Lingala", visible: true, emoji: "💬" },
  { id: "397", type: "language", name: "Lithuanian", visible: true, emoji: "💬" },
  { id: "398", type: "language", name: "Macedonian", visible: true, emoji: "💬" },
  { id: "399", type: "language", name: "Maithili", visible: true, emoji: "💬" },
  { id: "400", type: "language", name: "Malagasy", visible: true, emoji: "💬" },
  { id: "401", type: "language", name: "Malay", visible: true, emoji: "💬" },
  { id: "402", type: "language", name: "Malayalam", visible: true, emoji: "💬" },
  { id: "403", type: "language", name: "Mandarin", visible: true, emoji: "💬" },
  { id: "404", type: "language", name: "Marathi", visible: true, emoji: "💬" },
  { id: "405", type: "language", name: "Mende", visible: true, emoji: "💬" },
  { id: "406", type: "language", name: "Mongolian", visible: true, emoji: "💬" },
  { id: "407", type: "language", name: "Nahuatl", visible: true, emoji: "💬" },
  { id: "408", type: "language", name: "Navajo", visible: true, emoji: "💬" },
  { id: "409", type: "language", name: "Nepali", visible: true, emoji: "💬" },
  { id: "410", type: "language", name: "Norwegian", visible: true, emoji: "💬" },
  { id: "411", type: "language", name: "Ojibwa", visible: true, emoji: "💬" },
  { id: "412", type: "language", name: "Oriya", visible: true, emoji: "💬" },
  { id: "413", type: "language", name: "Oromo", visible: true, emoji: "💬" },
  { id: "414", type: "language", name: "Pashto", visible: true, emoji: "💬" },
  { id: "415", type: "language", name: "Persian", visible: true, emoji: "💬" },
  { id: "416", type: "language", name: "Polish", visible: true, emoji: "💬" },
  { id: "417", type: "language", name: "Portuguese", visible: true, emoji: "💬" },
  { id: "418", type: "language", name: "Punjabi", visible: true, emoji: "💬" },
  { id: "419", type: "language", name: "Quechua", visible: true, emoji: "💬" },
  { id: "420", type: "language", name: "Romani", visible: true, emoji: "💬" },
  { id: "421", type: "language", name: "Romanian", visible: true, emoji: "💬" },
  { id: "422", type: "language", name: "Russian", visible: true, emoji: "💬" },
  { id: "423", type: "language", name: "Rwanda", visible: true, emoji: "💬" },
  { id: "424", type: "language", name: "Samoan", visible: true, emoji: "💬" },
  { id: "425", type: "language", name: "Sanskrit", visible: true, emoji: "💬" },
  { id: "426", type: "language", name: "Serbian", visible: true, emoji: "💬" },
  { id: "427", type: "language", name: "Shona", visible: true, emoji: "💬" },
  { id: "428", type: "language", name: "Sindhi", visible: true, emoji: "💬" },
  { id: "429", type: "language", name: "Sinhala", visible: true, emoji: "💬" },
  { id: "430", type: "language", name: "Slovak", visible: true, emoji: "💬" },
  { id: "431", type: "language", name: "Slovene", visible: true, emoji: "💬" },
  { id: "432", type: "language", name: "Somali", visible: true, emoji: "💬" },
  { id: "433", type: "language", name: "Spanish", visible: true, emoji: "💬" },
  { id: "434", type: "language", name: "Swahili", visible: true, emoji: "💬" },
  { id: "435", type: "language", name: "Swedish", visible: true, emoji: "💬" },
  { id: "436", type: "language", name: "Tachelhit", visible: true, emoji: "💬" },
  { id: "437", type: "language", name: "Tagalog", visible: true, emoji: "💬" },
  { id: "438", type: "language", name: "Tajiki", visible: true, emoji: "💬" },
  { id: "439", type: "language", name: "Tamil", visible: true, emoji: "💬" },
  { id: "440", type: "language", name: "Tatar", visible: true, emoji: "💬" },
  { id: "441", type: "language", name: "Telugu", visible: true, emoji: "💬" },
  { id: "442", type: "language", name: "Thai", visible: true, emoji: "💬" },
  {
    id: "443",
    type: "language",
    name: "Tibetic Languages",
    visible: true,
    emoji: "💬",
  },
  { id: "444", type: "language", name: "Tigrigna", visible: true, emoji: "💬" },
  { id: "445", type: "language", name: "Tok Pisin", visible: true, emoji: "💬" },
  { id: "446", type: "language", name: "Turkish", visible: true, emoji: "💬" },
  { id: "447", type: "language", name: "Turkmen", visible: true, emoji: "💬" },
  { id: "448", type: "language", name: "Ukrainian", visible: true, emoji: "💬" },
  { id: "449", type: "language", name: "Urdu", visible: true, emoji: "💬" },
  { id: "450", type: "language", name: "Uyghur", visible: true, emoji: "💬" },
  { id: "451", type: "language", name: "Uzbek", visible: true, emoji: "💬" },
  { id: "452", type: "language", name: "Vietnamese", visible: true, emoji: "💬" },
  { id: "453", type: "language", name: "Warlpiri", visible: true, emoji: "💬" },
  { id: "454", type: "language", name: "Welsh", visible: true, emoji: "💬" },
  { id: "455", type: "language", name: "Wolof", visible: true, emoji: "💬" },
  { id: "456", type: "language", name: "Xhosa", visible: true, emoji: "💬" },
  { id: "457", type: "language", name: "Yakut", visible: true, emoji: "💬" },
  { id: "458", type: "language", name: "Yiddish", visible: true, emoji: "💬" },
  { id: "459", type: "language", name: "Yoruba", visible: true, emoji: "💬" },
  { id: "460", type: "language", name: "Yucatec", visible: true, emoji: "💬" },
  { id: "461", type: "language", name: "Zapotec", visible: true, emoji: "💬" },
  { id: "462", type: "language", name: "Zulu", visible: true, emoji: "💬" },
];

export const MEYER_BRIGGS = [
  {
    id: "463",
    type: "meyer_briggs",
    name: "ISTJ - The Inspector",
    visible: true,
    emoji: "🕵️",
  },
  {
    id: "464",
    type: "meyer_briggs",
    name: "ISTP - The Crafter",
    visible: true,
    emoji: "🔨",
  },
  {
    id: "465",
    type: "meyer_briggs",
    name: "ISFJ - The Protector",
    visible: true,
    emoji: "🛡️",
  },
  {
    id: "466",
    type: "meyer_briggs",
    name: "ISFP - The Artist",
    visible: true,
    emoji: "🎨",
  },
  {
    id: "467",
    type: "meyer_briggs",
    name: "INFJ - The Advocate",
    visible: true,
    emoji: "🗣️",
  },
  {
    id: "468",
    type: "meyer_briggs",
    name: "INFP - The Mediator",
    visible: true,
    emoji: "☮️",
  },
  {
    id: "469",
    type: "meyer_briggs",
    name: "INTJ - The Architect",
    visible: true,
    emoji: "🏛️",
  },
  {
    id: "470",
    type: "meyer_briggs",
    name: "INTP - The Thinker",
    visible: true,
    emoji: "🤔",
  },
  {
    id: "471",
    type: "meyer_briggs",
    name: "ESTP - The Persuader",
    visible: true,
    emoji: "🤝",
  },
  {
    id: "472",
    type: "meyer_briggs",
    name: "ESTJ - The Director",
    visible: true,
    emoji: "🎬",
  },
  {
    id: "473",
    type: "meyer_briggs",
    name: "ESFP - The Performer",
    visible: true,
    emoji: "🎭",
  },
  {
    id: "474",
    type: "meyer_briggs",
    name: "ESFJ - The Caregiver",
    visible: true,
    emoji: "🤗",
  },
  {
    id: "475",
    type: "meyer_briggs",
    name: "ENFP - The Champion",
    visible: true,
    emoji: "🏆",
  },
  {
    id: "476",
    type: "meyer_briggs",
    name: "ENFJ - The Giver",
    visible: true,
    emoji: "🎁",
  },
  {
    id: "477",
    type: "meyer_briggs",
    name: "ENTP - The Debater",
    visible: true,
    emoji: "💬",
  },
  {
    id: "478",
    type: "meyer_briggs",
    name: "ENTJ - The Commander",
    visible: true,
    emoji: "🎖️",
  },
];

export const ALCOHOL_USAGE = [
  {
    id: "479",
    type: "alcohol_usage",
    name: "Never",
    order: 1,
    visible: true,
    emoji: "🚫🍷",
  },
  {
    id: "480",
    type: "alcohol_usage",
    name: "Socially",
    order: 2,
    visible: true,
    emoji: "🍷",
  },
  {
    id: "481",
    type: "alcohol_usage",
    name: "Regularly",
    order: 3,
    visible: true,
    emoji: "🍷",
  },
];

export const SMOKING_USAGE = [
  {
    id: "482",
    type: "smoking_usage",
    name: "Never",
    order: 1,
    visible: true,
    emoji: "🚭",
  },
  {
    id: "483",
    type: "smoking_usage",
    name: "Socially",
    order: 2,
    visible: true,
    emoji: "🚬",
  },
  {
    id: "484",
    type: "smoking_usage",
    name: "Regularly",
    order: 3,
    visible: true,
    emoji: "🚬",
  },
];

export const TAGS: { [type: string]: Tag[] } = {
  physical_activity: PHYSICAL_ACTIVITY,
  physical_activity_frequency: PHYSICAL_ACTIVITY_FREQUENCY,
  drink: DRINKS,
  diet: DIET,
  date_options: DATE_OPTIONS,
  gender: GENDERS,
  zodiac: ZODIAC_SIGNS,
  language: LANGUAGES,
  meyer_briggs: MEYER_BRIGGS,
  drug_usage: DRUG_USAGE,
  alcohol_usage: ALCOHOL_USAGE,
  smoking_usage: SMOKING_USAGE,
  travel_goals: TRAVEL_GOALS,
  pets: PETS,
  music_genre: MUSIC_GENRE,
  book_genre: BOOK_GENRE,
  film_genre: FILM_GENRE,
  creative: CREATIVE,
  education: EDUCATION_LEVEL,
  ethnicity: ETHNICITY,
  religion: RELIGION,
  religious_practice: RELIGIOUS_PRACTICES,
  cannibis_usage: CANNABIS_USAGE,
  relationship_type: RELATIONSHIP_TYPE,
  relationship_goal: RELATIONSHIP_GOALS,
  parenting_goal: PARENTING_GOALS,
  politics: POLITICS,
  staying_in: STAYING_IN,
  going_out: GOING_OUT,
};

export const TAG_VISIBLE_TYPES = {
  home_town: "home_town",
  job: "job",
  company: "company",
  school: "school",
  personality: "personality",
  physical_activity: "physical_activity",
  physical_activity_frequency: "physical_activity_frequency",
  drink: "drink",
  diet: "diet",
  date_options: "date_options",
  gender: "gender",
  zodiac: "zodiac",
  language: "language",
  meyer_briggs: "meyer_briggs",
  drug_usage: "drug_usage",
  alcohol_usage: "alcohol_usage",
  smoking_usage: "smoking_usage",
  travel_goals: "travel_goals",
  pets: "pets",
  music_genre: "music_genre",
  book_genre: "book_genre",
  film_genre: "film_genre",
  creative: "creative",
  education: "education",
  ethnicity: "ethnicity",
  religion: "religion",
  religious_practice: "religious_practice",
  cannibis_usage: "cannibis_usage",
  relationship_type: "relationship_type",
  relationship_goal: "relationship_goal",
  parenting_goal: "parenting_goal",
  politics: "politics",
  staying_in: "staying_in",
  going_out: "going_out",
};

export const TAGS_BY_ID: TagsById = {};
Object.values(TAGS).forEach((array) =>
  array.reduce((acc, obj) => {
    acc[obj.id] = obj;
    return acc;
  }, TAGS_BY_ID)
);

export const TAGS_BY_NAME: TagsByName = {};
Object.values(TAGS).forEach((array) =>
  array.reduce((acc, obj) => {
    acc[obj.name] = obj;
    return acc;
  }, TAGS_BY_NAME)
);
