export const EDUCATION_LEVEL = [
  {
    name: 'high School',
  },
  {
    name: 'graduate',
  },
  {
    name: 'post graduate',
  },
  {
    name: 'prefer not to say',
  },
]

export const ETHNICITY = [
  {
    name: 'Asian',
  },
  {
    name: 'Arab',
  },
  {
    name: 'Black/African-descent',
  },
  {
    name: 'Hispanic/Latino',
  },
  {
    name: 'Native American',
  },
  {
    name: 'Pacific Islander',
  },
  {
    name: 'South Asian',
  },
  {
    name: 'White/Caucasian',
  },
]

export const RELIGION = [
  {
    name: 'Agnostic',
  },
  {
    name: 'Atheist',
  },
  {
    name: 'Buddhist',
  },
  {
    name: 'Catholic',
  },
  {
    name: 'Christian',
  },
  {
    name: 'Hindu',
  },
  {
    name: 'Jewish',
  },
  {
    name: 'Mormon',
  },
  {
    id: '820',
    name: 'Muslim',
    type: 'religion',
    order: null,
    visible: true,
    emoji: '👏',
  },
  {
    id: '821',
    name: 'Shinto',
    type: 'religion',
    order: null,
    visible: true,
    emoji: '👏',
  },
  {
    id: '822',
    name: 'Sikh',
    type: 'religion',
    order: null,
    visible: true,
    emoji: '👏',
  },
  {
    id: '823',
    name: 'Spiritual',
    type: 'religion',
    order: null,
    visible: true,
    emoji: '👏',
  },
  {
    id: '824',
    name: 'Zoroastrian',
    type: 'religion',
    order: null,
    visible: true,
    emoji: '👏',
  },
]

export const SPORTS = [
  {
    id: '720',
    name: 'archery',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏹',
  },
  {
    id: '721',
    name: 'badminton',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏸',
  },
  {
    id: '722',
    name: 'baseball',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '⚾',
  },
  {
    id: '723',
    name: 'basketball',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏀',
  },
  {
    id: '724',
    name: 'bowling',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🎳',
  },
  {
    id: '725',
    name: 'boxing',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🥊',
  },
  {
    id: '726',
    name: 'cricket',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏏',
  },
  {
    id: '727',
    name: 'curling',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🥌',
  },
  {
    id: '728',
    name: 'cycling',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🚴',
  },
  {
    id: '729',
    name: 'dancing',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '💃',
  },
  {
    id: '730',
    name: 'darts',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🎯',
  },
  {
    id: '731',
    name: 'fencing',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🤺',
  },
  {
    id: '732',
    name: 'figure skating',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '⛸',
  },
  {
    id: '733',
    name: 'fishing',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🎣',
  },
  {
    id: '734',
    name: 'football',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏈',
  },
  {
    id: '735',
    name: 'golf',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏌',
  },
  {
    id: '736',
    name: 'gymnastics',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🤸',
  },
  {
    id: '737',
    name: 'hang gliding',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🪂',
  },
  {
    id: '738',
    name: 'horse riding',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏇',
  },
  {
    id: '739',
    name: 'ice hockey',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏒',
  },
  {
    id: '740',
    name: 'ice skating',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '⛸',
  },
  {
    id: '741',
    name: 'jet skiing',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🚤',
  },
  {
    id: '742',
    name: 'judo',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🥋',
  },
  {
    id: '743',
    name: 'karate',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🥋',
  },
  {
    id: '744',
    name: 'kickboxing',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🥋',
  },
  {
    id: '745',
    name: 'lacrosse',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🥍',
  },
  {
    id: '746',
    name: 'pool',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🎱',
  },
  {
    id: '747',
    name: 'rock climbing',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🧗',
  },
  {
    id: '748',
    name: 'roller skating',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🛼',
  },
  {
    id: '749',
    name: 'rowing',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🚣',
  },
  {
    id: '750',
    name: 'rugby',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏉',
  },
  {
    id: '751',
    name: 'running',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '👟',
  },
  {
    id: '752',
    name: 'sailing',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '⛵',
  },
  {
    id: '753',
    name: 'scuba diving',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🤿',
  },
  {
    id: '754',
    name: 'skateboarding',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🛹',
  },
  {
    id: '755',
    name: 'skiing',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '⛷',
  },
  {
    id: '756',
    name: 'sky diving',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🪂',
  },
  {
    id: '757',
    name: 'snowboarding',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏂',
  },
  {
    id: '758',
    name: 'soccer',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '⚽',
  },
  {
    id: '759',
    name: 'surfing',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏄',
  },
  {
    id: '760',
    name: 'swimming',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏊',
  },
  {
    id: '761',
    name: 'table tennis',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏓',
  },
  {
    id: '762',
    name: 'taekwondo',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🥋',
  },
  {
    id: '763',
    name: 'tennis',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🎾',
  },
  {
    id: '764',
    name: 'volleyball',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏐',
  },
  {
    id: '765',
    name: 'water skiing',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '💦',
  },
  {
    id: '766',
    name: 'weight lifting',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🏋',
  },
  {
    id: '767',
    name: 'wind surfing',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '💨',
  },
  {
    id: '768',
    name: 'wrestling',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🤼',
  },
  {
    id: '769',
    name: 'yoga',
    type: 'physical_activity',
    order: null,
    visible: true,
    emoji: '🧘',
  },
]

export const ZODIAC = [
  {
    id: '775',
    name: 'Aries',
    type: 'zodiac',
    order: 1,
    visible: true,
    emoji: '♈',
  },
  {
    id: '776',
    name: 'Taurus',
    type: 'zodiac',
    order: 2,
    visible: true,
    emoji: '♉',
  },
  {
    id: '777',
    name: 'Gemini',
    type: 'zodiac',
    order: 3,
    visible: true,
    emoji: '♊',
  },
  {
    id: '778',
    name: 'Cancer',
    type: 'zodiac',
    order: 4,
    visible: true,
    emoji: '♋',
  },
  {
    id: '779',
    name: 'Leo',
    type: 'zodiac',
    order: 5,
    visible: true,
    emoji: '♌',
  },
  {
    id: '780',
    name: 'Virgo',
    type: 'zodiac',
    order: 6,
    visible: true,
    emoji: '♍',
  },
  {
    id: '781',
    name: 'Libra',
    type: 'zodiac',
    order: 7,
    visible: true,
    emoji: '♎',
  },
  {
    id: '782',
    name: 'Scorpio',
    type: 'zodiac',
    order: 8,
    visible: true,
    emoji: '♏',
  },
  {
    id: '783',
    name: 'Sagittarius',
    type: 'zodiac',
    order: 9,
    visible: true,
    emoji: '♐',
  },
  {
    id: '784',
    name: 'Capricorn',
    type: 'zodiac',
    order: 10,
    visible: true,
    emoji: '♑',
  },
  {
    id: '785',
    name: 'Aquarius',
    type: 'zodiac',
    order: 11,
    visible: true,
    emoji: '♒',
  },
  {
    id: '786',
    name: 'Pisces',
    type: 'zodiac',
    order: 12,
    visible: true,
    emoji: '♓',
  },
]

export const RELIGIOUS_PRACTICES = [
  {
    id: '825',
    name: 'not practicing',
    type: 'religion_practice',
    order: 1,
    visible: true,
    emoji: '🙏',
  },
  {
    id: '826',
    name: 'in faith / in belief',
    type: 'religion_practice',
    order: 2,
    visible: true,
    emoji: '🙏',
  },
  {
    id: '827',
    name: 'practicing when with family',
    type: 'religion_practice',
    order: 3,
    visible: true,
    emoji: '🙏',
  },
  {
    id: '828',
    name: 'moderate practice',
    type: 'religion_practice',
    order: 4,
    visible: true,
    emoji: '🙏',
  },
  {
    id: '829',
    name: 'active practice',
    type: 'religion_practice',
    order: 5,
    visible: true,
    emoji: '🙏',
  },
]

export const DRUG_USAGE = [
  {
    id: '830',
    name: 'Socially',
    type: 'drug_usage',
    order: 1,
    visible: true,
    emoji: '💉',
  },
  {
    id: '831',
    name: 'Never',
    type: 'drug_usage',
    order: 2,
    visible: true,
    emoji: '💉',
  },
  {
    id: '832',
    name: 'Regularly',
    type: 'drug_usage',
    order: 3,
    visible: true,
    emoji: '💉',
  },
  {
    id: '833',
    name: 'Medicinally',
    type: 'drug_usage',
    order: 4,
    visible: true,
    emoji: '💉',
  },
]

export const CANNABIS = [
  {
    id: '830',
    name: 'Socially',
    type: 'drug_usage',
    order: 1,
    visible: true,
    emoji: '',
  },
  {
    id: '831',
    name: 'Never',
    type: 'drug_usage',
    order: 2,
    visible: true,
    emoji: '',
  },
  {
    id: '832',
    name: 'Regularly',
    type: 'drug_usage',
    order: 3,
    visible: true,
    emoji: '',
  },
  {
    id: '833',
    name: 'Medicinally',
    type: 'drug_usage',
    order: 4,
    visible: true,
    emoji: '',
  },
]

export const SUBSTANCE_USAGE = [
  {
    id: '834',
    name: 'Socially',
    type: 'substance_usage',
    order: 1,
    visible: true,
    emoji: '',
  },
  {
    id: '835',
    name: 'Never',
    type: 'substance_usage',
    order: 2,
    visible: true,
    emoji: '',
  },
  {
    id: '836',
    name: 'Regularly',
    type: 'substance_usage',
    order: 3,
    visible: true,
    emoji: '',
  },
]

export const RELATIONSHIP_TYPE = [
  {
    id: '837',
    name: 'Monogomy',
    type: 'relationship_type',
    order: null,
    visible: true,
    emoji: '',
  },
  {
    id: '838',
    name: 'Non-Monogamy',
    type: 'relationship_type',
    order: null,
    visible: true,
    emoji: '',
  },
  {
    id: '839',
    name: 'Monogamish',
    type: 'relationship_type',
    order: null,
    visible: true,
    emoji: '',
  },
  {
    id: '840',
    name: 'Polygamy',
    type: 'relationship_type',
    order: null,
    visible: true,
    emoji: '',
  },
  {
    id: '841',
    name: 'Open',
    type: 'relationship_type',
    order: null,
    visible: true,
    emoji: '',
  },
  {
    id: '842',
    name: 'Swinging',
    type: 'relationship_type',
    order: null,
    visible: true,
    emoji: '',
  },
  {
    id: '843',
    name: 'Polyamory',
    type: 'relationship_type',
    order: null,
    visible: true,
    emoji: '',
  },
  {
    id: '844',
    name: 'Polyfidelity',
    type: 'relationship_type',
    order: null,
    visible: true,
    emoji: '',
  },
  {
    id: '845',
    name: 'Polyaffective',
    type: 'relationship_type',
    order: null,
    visible: true,
    emoji: '',
  },
  {
    id: '846',
    name: "Don't Know",
    type: 'relationship_type',
    order: null,
    visible: true,
    emoji: '',
  },
  {
    id: '847',
    name: 'Open to trying',
    type: 'relationship_type',
    order: null,
    visible: true,
    emoji: '',
  },
]

export const RELATIONSHIP_GOALS = [
  {
    id: '848',
    name: 'Marriage',
    type: 'relationship_goal',
    order: null,
    visible: true,
    emoji: '💍',
  },
  {
    id: '849',
    name: 'Something Casual',
    type: 'relationship_goal',
    order: null,
    visible: true,
    emoji: '👫',
  },
  {
    id: '850',
    name: 'Friendship',
    type: 'relationship_goal',
    order: null,
    visible: true,
    emoji: '👫',
  },
  {
    id: '851',
    name: "Don't know yet",
    type: 'relationship_goal',
    order: null,
    visible: true,
    emoji: '🤷‍♂️',
  },
  {
    id: '852',
    name: 'Relationship',
    type: 'relationship_goal',
    order: null,
    visible: true,
    emoji: '💏',
  },
]

export const PARENTING_GOALS = [
  {
    id: '853',
    name: 'Want someday',
    type: 'parenting_goal',
    order: null,
    visible: true,
    emoji: '👩‍🍼',
  },
  {
    id: '854',
    name: "Don't want",
    type: 'parenting_goal',
    order: null,
    visible: true,
    emoji: '👩‍🍼',
  },
  {
    id: '855',
    name: 'Undecided',
    type: 'parenting_goal',
    order: null,
    visible: true,
    emoji: '👩‍🍼',
  },
  {
    id: '856',
    name: 'Indifferent',
    type: 'parenting_goal',
    order: null,
    visible: true,
    emoji: '👩‍🍼',
  },
  {
    id: '857',
    name: 'Have and want more',
    type: 'parenting_goal',
    order: null,
    visible: true,
    emoji: '👩‍🍼',
  },
  {
    id: '858',
    name: "Have and don't want more",
    type: 'parenting_goal',
    order: null,
    visible: true,
    emoji: '👩‍🍼',
  },
  {
    id: '859',
    name: 'Have and undecided to more',
    type: 'parenting_goal',
    order: null,
    visible: true,
    emoji: '👩‍🍼',
  },
  {
    id: '860',
    name: 'Have and indifferent to more',
    type: 'parenting_goal',
    order: null,
    visible: true,
    emoji: '👩‍🍼',
  },
]

export const POLITICS = [
  {
    id: '861',
    name: 'Apolitical',
    type: 'politics',
    order: null,
    visible: true,
    emoji: '🚩',
  },
  {
    id: '862',
    name: 'Moderate',
    type: 'politics',
    order: null,
    visible: true,
    emoji: '🚩',
  },
  {
    id: '863',
    name: 'Liberal',
    type: 'politics',
    order: null,
    visible: true,
    emoji: '🚩',
  },
  {
    id: '864',
    name: 'Conservative',
    type: 'politics',
    order: null,
    visible: true,
    emoji: '🚩',
  },
]

export const CREATIVE = [
  {
    id: '865',
    name: 'Acting',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '866',
    name: 'Art',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '🎨',
  },
  {
    id: '867',
    name: 'Baking',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '🍰',
  },
  {
    id: '868',
    name: 'Blogging',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '👨',
  },
  {
    id: '869',
    name: 'Carpentry',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '🪚',
  },
  {
    id: '870',
    name: 'Coding',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '👩',
  },
  {
    id: '871',
    name: 'Comedy',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '🎭',
  },
  {
    id: '872',
    name: 'Cooking',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '🧑',
  },
  {
    id: '873',
    name: 'Crafts',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '✂',
  },
  {
    id: '874',
    name: 'Dancing',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '💃',
  },
  {
    id: '875',
    name: 'Design',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '👜',
  },
  {
    id: '876',
    name: 'Fashion',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '👠',
  },
  {
    id: '877',
    name: 'Gardening',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '🪴',
  },
  {
    id: '878',
    name: 'Interior / Exterior Renovations',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '🔨',
  },
  {
    id: '879',
    name: 'Make-up',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '💄',
  },
  {
    id: '880',
    name: 'Making / Writing music',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '🎶',
  },
  {
    id: '881',
    name: 'Making videoos',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '882',
    name: 'Painting',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '🎨',
  },
  {
    id: '883',
    name: 'Photography',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '📷',
  },
  {
    id: '884',
    name: 'Pottery',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '🫖',
  },
  {
    id: '885',
    name: 'Singing / Playing Music',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '🎶',
  },
  {
    id: '886',
    name: 'Theatre',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '🎞',
  },
  {
    id: '887',
    name: 'Writing',
    type: 'creative',
    order: null,
    visible: true,
    emoji: '✍',
  },
]

export const GOING_OUT = [
  {
    id: '888',
    name: 'Bars',
    type: 'going_out',
    order: null,
    visible: true,
    emoji: '🍸',
  },
  {
    id: '889',
    name: 'Concerts',
    type: 'going_out',
    order: null,
    visible: true,
    emoji: '🎵',
  },
  {
    id: '890',
    name: 'Festivals',
    type: 'going_out',
    order: null,
    visible: true,
    emoji: '🎫',
  },
  {
    id: '891',
    name: 'Museums & galleries',
    type: 'going_out',
    order: null,
    visible: true,
    emoji: '🖼',
  },
  {
    id: '892',
    name: 'Nightclubs',
    type: 'going_out',
    order: null,
    visible: true,
    emoji: '🎟',
  },
  {
    id: '893',
    name: 'Stand up',
    type: 'going_out',
    order: null,
    visible: true,
    emoji: '🎭',
  },
  {
    id: '894',
    name: 'Theater',
    type: 'going_out',
    order: null,
    visible: true,
    emoji: '🎞',
  },
]

export const STAYING_IN = [
  {
    id: '895',
    name: 'baking',
    type: 'staying_in',
    order: null,
    visible: true,
    emoji: '🍪',
  },
  {
    id: '896',
    name: 'cooking',
    type: 'staying_in',
    order: null,
    visible: true,
    emoji: '🍳',
  },
  {
    id: '897',
    name: 'board games',
    type: 'staying_in',
    order: null,
    visible: true,
    emoji: '🎲',
  },
  {
    id: '898',
    name: 'gardening',
    type: 'staying_in',
    order: null,
    visible: true,
    emoji: '👩',
  },
  {
    id: '899',
    name: 'takeout',
    type: 'staying_in',
    order: null,
    visible: true,
    emoji: '🥡',
  },
  {
    id: '900',
    name: 'video games',
    type: 'staying_in',
    order: null,
    visible: true,
    emoji: '🎮',
  },
  {
    id: '901',
    name: 'movies',
    type: 'staying_in',
    order: null,
    visible: true,
    emoji: '🍿',
  },
  {
    id: '902',
    name: 'TV series',
    type: 'staying_in',
    order: null,
    visible: true,
    emoji: '📺',
  },
]

export const FILE_GENRE = [
  {
    id: '903',
    name: 'Action & Adventure',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '904',
    name: 'Animated',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '905',
    name: 'Anime',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '906',
    name: 'Bollywood',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '907',
    name: 'Comedy',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '908',
    name: 'Cooking shows',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '909',
    name: 'Crime',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '910',
    name: 'Documentaries',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '911',
    name: 'Drama',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '912',
    name: 'Fantasy',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '913',
    name: 'Game Shows',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '914',
    name: 'Horror',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '915',
    name: 'Indie',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '916',
    name: 'Mystery',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '917',
    name: 'Reality Shows',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '918',
    name: 'Rom-com',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '919',
    name: 'Romance',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '920',
    name: 'Sci-fi',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '921',
    name: 'Superhero',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
  {
    id: '922',
    name: 'Thriller',
    type: 'film_genre',
    order: null,
    visible: true,
    emoji: '🎬',
  },
]

export const BOOK_GENRE = [
  {
    id: '923',
    name: 'Action & Adventure',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '924',
    name: 'Biographies',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '925',
    name: 'Classics',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '926',
    name: 'Comedy',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '927',
    name: 'Comic books',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '928',
    name: 'Crime',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '929',
    name: 'Fantasy',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '930',
    name: 'History',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '931',
    name: 'Horror',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '932',
    name: 'Manga',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '933',
    name: 'Mystery',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '934',
    name: 'Philosophy',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '935',
    name: 'Poetry',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '936',
    name: 'Psychology',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '937',
    name: 'Romance',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '938',
    name: 'Sci-fi',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '939',
    name: 'Science',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '940',
    name: 'Thriller',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
  {
    id: '941',
    name: 'Non-fiction',
    type: 'book_genre',
    order: null,
    visible: true,
    emoji: '📚',
  },
]

export const MUSIC_GENRE = [
  {
    id: '942',
    name: 'Afro',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '943',
    name: 'Arab',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '944',
    name: 'Blues',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '945',
    name: 'Classsical',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '946',
    name: 'Country',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '947',
    name: 'Desi',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '948',
    name: 'EDM',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '949',
    name: 'Electronic',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '950',
    name: 'Folk & Acoustic',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '951',
    name: 'Funk',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '952',
    name: 'Hip Hop',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '953',
    name: 'House',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '954',
    name: 'Indie',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '955',
    name: 'Jazz',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '956',
    name: 'K-pop',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '957',
    name: 'Latin',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '958',
    name: 'Metal',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '959',
    name: 'Pop',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '960',
    name: 'Punk',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '961',
    name: 'R&B',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '962',
    name: 'Rap',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '963',
    name: 'Reggae',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '964',
    name: 'Rock',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '965',
    name: 'Soul',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
  {
    id: '966',
    name: 'Techno',
    type: 'music_genre',
    order: null,
    visible: true,
    emoji: '🎤',
  },
]

export const DIET = [
  {
    id: '989',
    name: 'Vegan',
    type: 'diet',
    order: null,
    visible: true,
    emoji: '🍽️',
  },
  {
    id: '990',
    name: 'Vegetarian',
    type: 'diet',
    order: null,
    visible: true,
    emoji: '🍽️',
  },
  {
    id: '991',
    name: 'Gluten Free',
    type: 'diet',
    order: null,
    visible: true,
    emoji: '🍽️',
  },
  {
    id: '992',
    name: 'Halal',
    type: 'diet',
    order: null,
    visible: true,
    emoji: '🍽️',
  },
  {
    id: '993',
    name: 'Pescatarian',
    type: 'diet',
    order: null,
    visible: true,
    emoji: '🍽️',
  },
  {
    id: '994',
    name: 'Paleo',
    type: 'diet',
    order: null,
    visible: true,
    emoji: '🍽️',
  },
  {
    id: '995',
    name: 'Kosher',
    type: 'diet',
    order: null,
    visible: true,
    emoji: '🍽️',
  },
  {
    id: '996',
    name: 'Keto',
    type: 'diet',
    order: null,
    visible: true,
    emoji: '🍽️',
  },
  {
    id: '997',
    name: 'Dairy Free',
    type: 'diet',
    order: null,
    visible: true,
    emoji: '🍽️',
  },
  {
    id: '998',
    name: 'Peanut Free',
    type: 'diet',
    order: null,
    visible: true,
    emoji: '🍽️',
  },
  {
    id: '999',
    name: 'Nut free',
    type: 'diet',
    order: null,
    visible: true,
    emoji: '🍽️',
  },
  {
    id: '1000',
    name: 'Intermitent Fasting',
    type: 'diet',
    order: null,
    visible: true,
    emoji: '🍽️',
  },
]

export const PETS = [
  {
    id: '1012',
    name: 'Bird',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐦',
  },
  {
    id: '1013',
    name: 'Cat',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐱',
  },
  {
    id: '1014',
    name: 'Crustacean',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐌',
  },
  {
    id: '1015',
    name: 'Dog',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐶',
  },
  {
    id: '1016',
    name: 'Ferret / Weasel',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🦡',
  },
  {
    id: '1017',
    name: 'Fish',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐠',
  },
  {
    id: '1018',
    name: 'Goat',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐐',
  },
  {
    id: '1019',
    name: 'Guinea Pig',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐹',
  },
  {
    id: '1020',
    name: 'Hamster',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐹',
  },
  {
    id: '1021',
    name: 'Hedgehog',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🦔',
  },
  {
    id: '1022',
    name: 'Horse',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐴',
  },
  {
    id: '1023',
    name: 'Insect',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐛',
  },
  {
    id: '1024',
    name: 'Mouse',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐭',
  },
  {
    id: '1025',
    name: 'Pig',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐷',
  },
  {
    id: '1026',
    name: 'Rabbit',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐰',
  },
  {
    id: '1027',
    name: 'Reptile',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐸',
  },
  {
    id: '1028',
    name: 'Sheep',
    type: 'pets',
    order: null,
    visible: true,
    emoji: '🐑',
  },
]

export const DRINKS = [
  {
    id: '967',
    name: 'Aperitif',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '968',
    name: 'Beer',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '969',
    name: 'Boba tea',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '970',
    name: 'Cocktails',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '971',
    name: 'Coffee',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '972',
    name: 'Cold pressed juice',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '973',
    name: 'Energy Drink',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '974',
    name: 'Expresso',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '975',
    name: 'Gin',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '976',
    name: 'Hot chocolate',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '977',
    name: 'Juice',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '978',
    name: 'Kombucha',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '979',
    name: 'Latte / Cappuccino',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '980',
    name: 'Mezcal',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '981',
    name: 'Pop Soda',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🥤',
  },
  {
    id: '982',
    name: 'Protein Shake',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '983',
    name: 'Smoothie',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '984',
    name: 'Sports Drink / Electrolytes',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '985',
    name: 'Tea',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '986',
    name: 'Tequila',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '987',
    name: 'Whisky',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
  {
    id: '988',
    name: 'Wine',
    type: 'drink',
    order: null,
    visible: true,
    emoji: '🍷',
  },
]

export const LANGUAGES = [
  {
    id: '1034',
    name: 'Afrikaans',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1035',
    name: 'Albanian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1036',
    name: 'Amharic',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1037',
    name: 'Arabic',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1038',
    name: 'Aramaic',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1039',
    name: 'Armenian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1040',
    name: 'Assamese',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1041',
    name: 'Aymara',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1042',
    name: 'Azerbaijani',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1043',
    name: 'Balochi',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1044',
    name: 'Bamanankan',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1045',
    name: 'Bashkort (Bashkir)',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1046',
    name: 'Basque',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1047',
    name: 'Belarusan',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1048',
    name: 'Bengali',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1049',
    name: 'Bhojpuri',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1050',
    name: 'Bislama',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1051',
    name: 'Bosnian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1052',
    name: 'Brahui',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1053',
    name: 'Bulgarian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1054',
    name: 'Burmese',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1055',
    name: 'Cantonese',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1056',
    name: 'Catalan',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1057',
    name: 'Cebuano',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1058',
    name: 'Chechen',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1059',
    name: 'Cherokee',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1060',
    name: 'Croatian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1061',
    name: 'Czech',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1062',
    name: 'Dakota',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1063',
    name: 'Danish',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1064',
    name: 'Dari',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1065',
    name: 'Dholuo',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1066',
    name: 'Dutch',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1067',
    name: 'English',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1068',
    name: 'Esperanto',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1069',
    name: 'Estonian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1070',
    name: 'Éwé',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1071',
    name: 'Finnish',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1072',
    name: 'French',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1073',
    name: 'Georgian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1074',
    name: 'German',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1075',
    name: 'Gikuyu',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1076',
    name: 'Greek',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1077',
    name: 'Guarani',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1078',
    name: 'Gujarati',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1079',
    name: 'Haitian Creole',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1080',
    name: 'Hausa',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1081',
    name: 'Hawaiian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1082',
    name: 'Hawaiian Creole',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1083',
    name: 'Hebrew',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1084',
    name: 'Hiligaynon',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1085',
    name: 'Hindi',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1086',
    name: 'Hungarian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1087',
    name: 'Icelandic',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1088',
    name: 'Igbo',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1089',
    name: 'Ilocano',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1090',
    name: 'Indonesian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1091',
    name: 'Inuit/Inupiaq',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1092',
    name: 'Irish Gaelic',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1093',
    name: 'Italian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1094',
    name: 'Japanese',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1095',
    name: 'Jarai',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1096',
    name: 'Javanese',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1097',
    name: 'K’iche’',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1098',
    name: 'Kabyle',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1099',
    name: 'Kannada',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1100',
    name: 'Kashmiri',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1101',
    name: 'Kazakh',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1102',
    name: 'Khmer',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1103',
    name: 'Khoekhoe',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1104',
    name: 'Korean',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1105',
    name: 'Kurdish',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1106',
    name: 'Kyrgyz',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1107',
    name: 'Lao',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1108',
    name: 'Latin',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1109',
    name: 'Latvian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1110',
    name: 'Lingala',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1111',
    name: 'Lithuanian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1112',
    name: 'Macedonian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1113',
    name: 'Maithili',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1114',
    name: 'Malagasy',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1115',
    name: 'Malay',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1116',
    name: 'Malayalam',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1117',
    name: 'Mandarin',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1118',
    name: 'Marathi',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1119',
    name: 'Mende',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1120',
    name: 'Mongolian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1121',
    name: 'Nahuatl',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1122',
    name: 'Navajo',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1123',
    name: 'Nepali',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1124',
    name: 'Norwegian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1125',
    name: 'Ojibwa',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1126',
    name: 'Oriya',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1127',
    name: 'Oromo',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1128',
    name: 'Pashto',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1129',
    name: 'Persian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1130',
    name: 'Polish',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1131',
    name: 'Portuguese',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1132',
    name: 'Punjabi',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1133',
    name: 'Quechua',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1134',
    name: 'Romani',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1135',
    name: 'Romanian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1136',
    name: 'Russian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1137',
    name: 'Rwanda',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1138',
    name: 'Samoan',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1139',
    name: 'Sanskrit',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1140',
    name: 'Serbian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1141',
    name: 'Shona',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1142',
    name: 'Sindhi',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1143',
    name: 'Sinhala',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1144',
    name: 'Slovak',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1145',
    name: 'Slovene',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1146',
    name: 'Somali',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1147',
    name: 'Spanish',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1148',
    name: 'Swahili',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1149',
    name: 'Swedish',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1150',
    name: 'Tachelhit',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1151',
    name: 'Tagalog',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1152',
    name: 'Tajiki',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1153',
    name: 'Tamil',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1154',
    name: 'Tatar',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1155',
    name: 'Telugu',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1156',
    name: 'Thai',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1157',
    name: 'Tibetic Languages',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1158',
    name: 'Tigrigna',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1159',
    name: 'Tok Pisin',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1160',
    name: 'Turkish',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1161',
    name: 'Turkmen',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1162',
    name: 'Ukrainian',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1163',
    name: 'Urdu',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1164',
    name: 'Uyghur',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1165',
    name: 'Uzbek',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1166',
    name: 'Vietnamese',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1167',
    name: 'Warlpiri',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1168',
    name: 'Welsh',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1169',
    name: 'Wolof',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1170',
    name: 'Xhosa',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1171',
    name: 'Yakut',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1172',
    name: 'Yiddish',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1173',
    name: 'Yoruba',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1174',
    name: 'Yucatec',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1175',
    name: 'Zapotec',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
  {
    id: '1176',
    name: 'Zulu',
    type: 'laguage',
    order: null,
    visible: true,
    emoji: '💬',
  },
]

export const MEYER_BRIGGS = [
  {
    name: 'ISTJ - The Inspector',
  },
  {
    name: 'ISTP - The Crafter',
  },
  {
    name: 'ISFJ - The Protector',
  },
  {
    name: 'ISFP - The Artist',
  },
  {
    name: 'INFJ - The Advocate',
  },
  {
    name: 'INFP - The Mediator',
  },
  {
    name: 'INTJ - The Architect',
  },
  {
    name: 'INTP - The Thinker',
  },
  {
    name: 'ESTP - The Persuader',
  },
  {
    name: 'ESTJ - The Director',
  },
  {
    name: 'ESFP - The Performer',
  },
  {
    name: 'ESFJ - The Caregiver',
  },
  {
    name: 'ENFP - The Champion',
  },
  {
    name: 'ENFJ - The Giver',
  },
  {
    name: 'ENTP - The Debater',
  },
  {
    name: 'ENTJ - The Commander',
  },
]

export const ALCOHOL = [
  {
    name: 'Socially',
  },
  {
    name: 'Never',
  },
  {
    name: 'Regularly',
  },
]

export const DRUGS = [
  {
    name: 'Socially',
  },
  {
    name: 'Never',
  },
  {
    name: 'Regularly',
  },
]

export const SMOKING = [
  {
    name: 'Socially',
  },
  {
    name: 'Never',
  },
  {
    name: 'Regularly',
  },
]

export const TagInitialData = {
  id: '',
  name: '',
  type: '',
  order: null,
  visible: true,
  emoji: '',
}
